### ISSUE TITLE
Handle URL with spaces

### ISSUE THREAD

**Issue by chinyeungli** [aboutcode-org/aboutcode-toolkit#1]
The current validation method doesn't handle URL with spaces. Although it is very less likely there is any URL contains spaces, it happens.

Reference:
http://en.wikipedia.org/wiki/URL_normalization
https://pypi.python.org/pypi/urlnorm
http://code.google.com/p/google-url/

**Comment by chinyeungli** [comment]
perhaps we can use the urllib.quote()

urllib.quote(full_url, safe="%/:=&?~#+!$,;'@()*[]")

**Comment by pombredanne** [comment]
IMHO the URLs should be entered without spaces in the first place. This has been too rare to keep as an open ticket. I am closing for now as wontfix. Feel free to reopen, of course!
