### ISSUE TITLE
Check that everything in a dir is documented by ABOUT files

### ISSUE THREAD

**Issue by pombredanne** [aboutcode-org/aboutcode-toolkit#10]
We should have a feature such that given a directory, it will parse ABOUT files, and ensure that all files in the directory are directly or indirectly (ie from a parent directory) documented or referenced in an ABOUT file

**Comment by jdaguil** [comment]
@pombredanne can you explain this a little more..?

**Comment by pombredanne** [comment]
@jdaguil I often store all my third party code in one dir. I would like to point to the tool that dir and ensure that all files in this dir are either ABOUT files or files or dir documented by an ABOUT file, ie checking that all the origin of all files and dir in a dir are properly documented.
This will help me find orphaned files (such as an old notice no longer used) and undocumented files for which I should add an ABOUT file

**Comment by chinyeungli** [comment]
Similar issue in #24

**Comment by chinyeungli** [comment]
@pombredanne 
Let see if I have a component which the whole codebase is under apache-2.0. 
Then, I will have a ABOUT file placed in the root of the component.

However, there are cases that the component contains build scripts/config files which are under gpl-2.0 which should not consider as the license for the component.
Should these script/config files also be included in this ABOUT file?

**Comment by grv87** [comment]
> However, there are cases that the component contains build scripts/config files which are under gpl-2.0 which should not consider as the license for the component.

If ABOUT file says `about_resource: .`, doesn't it say that it covers all content of the directory?
If so, then it could have separate `excluding` field.

> all files in the directory are directly or indirectly (ie from a parent directory) documented or referenced in an ABOUT file

What if some files or subdirectories are temporary (like `build` subdirectory)? You need something like `.gitignore`.

**Comment by chinyeungli** [comment]
We have introduced the `ignored_resources`. Closing this.
