### ISSUE TITLE
Detect changes for files/directories

### ISSUE THREAD

**Issue by chinyeungli** [aboutcode-org/aboutcode-toolkit#107]
From pombredanne:
I have a clear solution in mind and that is not about detecting changes in general, but only changes to a single file (based on checksum) or dir (checksum of file checksums) pointed by the about_resource
and having a way to ensure that given about files, these checksums referenced in the about are still correct
The checksum is supported in the About spec

**Comment by pombredanne** [comment]
IMHO this can be closed as well as #303 as explained in https://github.com/nexB/aboutcode-toolkit/issues/303#issuecomment-346347039
