### ISSUE TITLE
Define how we are packaging ABOUT

### ISSUE THREAD

**Issue by pombredanne** [aboutcode-org/aboutcode-toolkit#11]
For now a simple .py script is best. 
Later we need to have extra libs and the single file approach will no longer work. 
We need to pick what packaging works knowing that target users may not be python developers. Some possibilities include:
- sdist on Pypi for Python developers. see #4 
- pyz zip for general usage that requires a Python installation
- py2exe, pyinstaller or similar for Windows/Mac/Linux that could work without a Python installed

Should ABOUT be system-wide installed? with man pages? as .deb or .rpm packages?

**Comment by tdruez** [comment]
Another solution could be the "The Wheel Binary Package Format" http://www.python.org/dev/peps/pep-0427/

**Comment by chinyeungli** [comment]
Closing this as I think the current pypi package does the work.
