### ISSUE TITLE
Create and Publish documentation to rtfd.org

### ISSUE THREAD

**Issue by chinyeungli** [aboutcode-org/aboutcode-toolkit#120]
using rst and generating a web site for doc. which should end up published on http://rtfd.org (aka http://readthedocs.org)

**Comment by chinyeungli** [comment]
@pombredanne is this still need?

**Comment by pombredanne** [comment]
@chinyeungli yes: we eventually want to have 1. a generated documentation 2. have this published automatically on rtfd. Since I am working on this too for ScanCode, you can hold on the publication part and focus only on the doc creation and generation part for now.

**Comment by mjherzog** [comment]
Now that we have an AboutCode website at ReadtheDocs - https://aboutcode.readthedocs.io/en/latest/index.html#, the last step is to move the AboutCode Toolkit part to a new, separate website for AboutCode Toolkit and sync documentation updates to code update for the Toolkit.
This will leave AboutCode as a website for documentation that applies across all AboutCode.org projects. In that context, it seems reasonable to keep ABC Data on the AboutCode website.

**Comment by chinyeungli** [comment]
@mjherzog sorry, I am not sure I understand what to do next.
I think all the doc for aboutcode-toolkit are already in https://aboutcode.readthedocs.io/en/latest/aboutcode-toolkit/index.html

**Comment by mjherzog** [comment]
@chinyeungli The current doc is there. The task here is to move the doc to a new top level doc - e.g. https://aboutcode-toolkit.readthedocs.io/ and move the doc "source" from the nexb/aboutcode repo in GH to nexb/aboutcode-toolkit. @johnmhoran can assist, but it would be good for you to also become familiar with how we build RTD doc using Sphinx.

**Comment by chinyeungli** [comment]
See https://github.com/nexB/aboutcode-toolkit/issues/424

**Comment by c02kr** [comment]
sir , I'm interested to work on this issue please assign this to me. As I am new to this repo I request you to guide me through it.

**Comment by mjherzog** [comment]
@CH-ND-N We are blocked at the moment because an over-eager volunteer previously pushed a shell document to RTD.org. We need to recover the site and relink it with this repo to move forward.

**Comment by chinyeungli** [comment]
sent an email to support@readthedocs.org and ask for help to regain access/ownership of the RTD page: https://aboutcode-toolkit.readthedocs.io/en/latest/

**Comment by mjherzog** [comment]
@chinyeungli check your emails from 10/27 to 10/28 - they said they made the transfer to us (you are on the email CC)

**Comment by mjherzog** [comment]
Now that we have control of https://readthedocs.org/projects/aboutcode-toolkit/, we need to move the all of the aboutcode-toolkit content from https://aboutcode.readthedocs.io/en/latest/aboutcode-toolkit/index.html# to https://readthedocs.org/projects/aboutcode-toolkit/
And remove it from https://readthedocs.org/projects/aboutcode-toolkit/.
We also need to cross-check that we have all of the relevant/current information from https://github.com/nexB/aboutcode-toolkit/wiki included at ttps://readthedocs.org/projects/aboutcode-toolkit/ and remove it from the wiki.

For the Specification section - https://aboutcode.readthedocs.io/en/latest/aboutcode-toolkit/specification.html - we should move this to the aboutcode-toolkit RTD page and provide a link from the ABCD section to the specification.

**Comment by mjherzog** [comment]
Also we need to review the current documentation to use "ABOUT file(s)" when we mean that and only use  "AboutCode Toolkit files" for input control files, Jinja templates and other processing artifacts.
