### ISSUE TITLE
Add dje_license_url field. This can be generated during the genabout.py (--extract_license)

### ISSUE THREAD

**Issue by chinyeungli** [aboutcode-org/aboutcode-toolkit#132]

**Comment by chinyeungli** [comment]
We can do the same approach as 'license_text_file'.
That's if there is already value in 'dje_license_url', then the code do nothing. However, if it's blank, then the code will automatically fill in this filled? (of course ONLY when user have set the --extract_license option)

**Comment by DennisClark** [comment]
The code should return the URL that belongs to the Dataspace of the User that is specified for the API.

**Comment by chinyeungli** [comment]
The 'dje_license_url' should be something like:
https://enterprise.dejacode.com/urn/?urn=urn:dje:license:"license_key"

as this is not DS-specific, only host specific
