### ISSUE TITLE
Add support for custom output in about.py

### ISSUE THREAD

**Issue by tdruez** [aboutcode-org/aboutcode-toolkit#139]
Similar to the mapping support in genabout.

When generating my csv from my About files, I'll like a custom set and order of columns.

Here's a mapping example:

```
name: Name
version: Version
dje_license: DejaCode License
home_url: Homepage
```

The output should look like:

| Name | Version | DejaCode License | Homepage |
| --- | --- | --- | --- |
| name1 | version1 | license1 | homepage1 |
| name2 | version2 | license2 | homepage2 |
| ... | ... | ... | ... |

**Comment by pombredanne** [comment]
Could a custom template work instead? to generate a CSV or a nicely justified list like with this?

```
======================= ============ ============================ ============================================================
Name                    Version      License                      Homepage
======================= ============ ============================ ============================================================
{% for about_object in about_objects -%}
{{ about_object.name.ljust(24) +}} {{ about_object.version.ljust(12) +}} {{ about_object.dje_license.ljust(28) +}} {{about_object.home_url}}
{% endfor -%}

```

**Comment by chinyeungli** [comment]
For some reasons, the fix in https://github.com/dejacode/about-code-tool/commit/8212969cf6a9e5638a5b69b7e5b99d509e160f2f is lost.

@DennisClark I just want to confirm that if a user provide a MAPPING.CONFIG file, ONLY the keys in the MAPPING.CONFIG will be used in the output CSV. The rest will not be included. Is that correct?

**Comment by chinyeungli** [comment]
actually this was not fixed. The output CSV inventory BOM doesn't have the custom column key.
