### ISSUE TITLE
move spec to gihub

### ISSUE THREAD

**Issue by pombredanne** [aboutcode-org/aboutcode-toolkit#140]

**Comment by pombredanne** [comment]
See https://github.com/dejacode/ABOUTspec ... next step will be to use that for the web site

**Comment by pombredanne** [comment]
@jdaguil what do you suggest to the web site side?

**Comment by chinyeungli** [comment]
https://github.com/nexB/aboutcode-toolkit/blob/develop/SPECIFICATION.rst
