### ISSUE TITLE
One central place for keys mapping and API information of the '--extract_license'

### ISSUE THREAD

**Issue by chinyeungli** [aboutcode-org/aboutcode-toolkit#165]
We have to separate the mapping file into 2 parts. One for the keys mapping, and the other for the api information.

If only '--mapping' is flagged, the tool will only look at the keys mapping section. Same situation for the '--extract_license'.

We don't need any arguments for the '--extract_license'.

**Comment by pombredanne** [comment]
Mapping should be limited in usage ... and not mixed with configuration. I am closing this as wontfix
