### ISSUE TITLE
Have an option for about.py to input a filter list to generate data for the filtered components

### ISSUE THREAD

**Issue by chinyeungli** [aboutcode-org/aboutcode-toolkit#166]
A project can contains many ABOUT files. However, sometimes, user may not be interested to have all the ABOUT files' information in the output spreadsheet. Instead, they may only be interested in subset of it.
As a result, it'll be convenience for user to input a filter list and ask the tool to only get the information from the filtered ABOUT files.

**Comment by mjherzog** [comment]
The most common case will be to generate a list based on a Product BOM - i.e. a list of Deployed components.

**Comment by DennisClark** [comment]
appears to be closed by mistake.  re-opening.

**Comment by chinyeungli** [comment]
similar issue #139

**Comment by chinyeungli** [comment]
This is different than #139. This issue is about `inventory` subset of ABOUT files while the #139 is about the format of the `inventory`
