### ISSUE TITLE
Return error if a directory is not readable

### ISSUE THREAD

**Issue by pombredanne** [aboutcode-org/aboutcode-toolkit#17]
Currently the  tool will skip a directory without returning any error message if a directory is not readable

**Comment by chinyeungli** [comment]
I created a non-readable directory (i.e. permission = 000)
For some reason, the `os.access(location, os.R_OK)` pass. The code stop at the
```
for base_dir, _, files in os.walk(location):
```
in the get_location function.

Will dig deeper and investigate more later.

**Comment by chinyeungli** [comment]
I created a directory with permission `000`
```
d---------+ 1 CYL CYL   0 May 22 16:30 nonreadable
```
However, the following code retruns
```
 print(os.access(location, os.R_OK))
print(os.access(location, os.W_OK))
import stat
print(stat.S_IMODE(os.stat(location).st_mode))
```
```
True
True
511
```

Not quite understand why the `000` permission directory still have `read` and `write` access as `True`, and the `000` becomes `511`

Will need more researches.

**Comment by pombredanne** [comment]
This is fixed in the https://github.com/nexB/aboutcode-toolkit/tree/361-make-transform-work
There is no tests for this though as testing permissions is notoriously difficult especially to clean up test files made unreadable and to get these to work on multiple OSes. This has been tested locally though:
```
$ mkdir tmp/unreadable
$ touch tmp/unreadable/that.ABOUT
$ chmod ugo-rwx tmp/unreadable/that.ABOUT
$ chmod ugo-rwx tmp/unreadable
$ find tmp -ls
 13511342      4 drwxrwxr-x   3 pombreda pombreda     4096 Dec 27 14:42 tmp
 13511360      4 d---------   2 pombreda pombreda     4096 Dec 27 14:43 tmp/unreadable
find: ‘tmp/unreadable’: Permission denied

$ about inventory tmp/ that.csv --verbose
Running aboutcode-toolkit version 4.0.0.pre1
Collecting inventory from ABOUT files...
Command completed with 1 errors or warnings.
CRITICAL: [Errno 13] Permission denied: 'tmp/unreadable'
Inventory collected in that.csv
```
