### ISSUE TITLE
Need source for UsingAboutCodetoDocumentYourSoftwareAssets

### ISSUE THREAD

**Issue by chinyeungli** [aboutcode-org/aboutcode-toolkit#173]
We need source for UsingAboutCodetoDocumentYourSoftwareAssets for the version control system.

https://github.com/dejacode/about-code-tool/blob/master/docs/UsingAboutCodetoDocumentYourSoftwareAssets.pdf

**Comment by DennisClark** [comment]
https://docs.google.com/document/d/1kP_LDQI6Ct-VQa0ME4ZkwXvkS9NRmvsnalivPFQ12qA/edit

**Comment by DennisClark** [comment]
Hi Chin Yeung, I provided a link to the Google Doc.  Please use that for the version control.

**Comment by chinyeungli** [comment]
okay. thanks.. I will need to convert this to .rst format

**Comment by chinyeungli** [comment]
Actually the codeblock is mis-formatted.
