### ISSUE TITLE
Need help/direction on how to fix test_About_equals_with_small_text_differences in test_model.py

### ISSUE THREAD

**Issue by chinyeungli** [aboutcode-org/aboutcode-toolkit#188]
The test fails for "self.assertEqual(a.dumps(True), b.dumps(True))"

Because
1. 
         license: |
       +     public-domain
             apache-2.0
       -     public-domain

License value order are different
1. 
   - copyright: Copyright (c) 2013-2014 nexB Inc.
   - copyright: Copyright (c) 2013-2014   nexB Inc.

Extra spaces in copyright notice.

The dumps function doesn't strip spaces or change order of values.
I think it will fail because it compares the output AFTER the process instead of compare value on the go.

Perhaps we need to create a function to compare value instead of the whole file instead?

**Comment by pombredanne** [comment]
I do think we need to handle ABOUT objects with small text differences as being equal for now. We can always revisit in the future... I am deleting the branch for this
