### ISSUE TITLE
refine/document error handling

### ISSUE THREAD

**Issue by chinyeungli** [aboutcode-org/aboutcode-toolkit#189]
What is best practice for error logs - always create one and empty means no errors or no log if no errors?

We need to have some "debugging" section in doc explaining how we handle errors and logs

**Comment by mjherzog** [comment]
Best practice imho is to provide a runtime report that can cover both simple statistics and errors or warnings when applicable. The purpose is to give a user concrete feedback.

For a run without errors, the output can be very simple statistics like the total run-time (in seconds?) and the number of records processed which would vary per process.  One approach for number of records would be to count the number of .ABOUT files created for genabout, and the number reported for about or genattrib.
would be to count the number of .ABOUT files created for genabout, and the number reported for about, updated

**Comment by chinyeungli** [comment]
I think we can close this.
The tool has already provided simple stats such as number of ABOUT files created and error (if any)
I don't think the run-time is needed as it runs pretty fast, and it doesn't give any useful information.
