### ISSUE TITLE
Tool halt if user ask to generate ABOUT Files in an invalid path

### ISSUE THREAD

**Issue by chinyeungli** [aboutcode-org/aboutcode-toolkit#198]
For instance,

```
/about_files/Repo/.../com/
```

On Windows, it'll give

```
WindowsError: [Error 3] The system cannot find the path specified: <path>
```

The tool should not be halted but log an error and continue the generation.

**Comment by pombreda** [comment]
Alternatively we good  either fail or log the error, for instance with a --keep-going option?
may be it is too much.

**Comment by chinyeungli** [comment]
That's indeed an idea to consider, but I think I will choose log the error for now

**Comment by chinyeungli** [comment]
This has been long fixed.
