### ISSUE TITLE
Enhance genabout.py to interpret a license expression when extracting license data

### ISSUE THREAD

**Issue by DennisClark** [aboutcode-org/aboutcode-toolkit#201]
Enhance genabout.py to handle a license expression in dje_license_key  — this is especially important/useful for conjunctive cases, but also for disjunctive when the intention is to pass the choice on to the next recipient of a package. 

So for example, something like this would appear in the generated .ABOUT file: 

dje_license_key: mit and bsd-new

dje_license_name: MIT License
dje_license_url: {{URL}}urn=urn:dje:license:mit
license_text_file: mit.LICENSE

dje_license_name: BSD-Modified
dje_license_url: {{URL}}urn=urn:dje:license:bsd-new
license_text_file: bsd-new.LICENSE

**Comment by mjherzog** [comment]
We would need to think about how to represent conjunctive (AND) or disjunctive (OR) in the .ABOUT file

**Comment by chinyeungli** [comment]
Following are the sample input and the output from the current code (version 3.0.2):
**Input (sample.json):**
```
[
  {
    "about_file_path": "/load/this.ABOUT", 
    "about_resource_path": ".", 
    "about_resource": ".", 
    "name": "AboutCode", 
    "version": "0.11.0",
    "license_expression": "bsd-new AND apache-2.0"
  }
]
```
**Command:**
```
(aboutcode-toolkit) C:\Users\CYL\git\aboutcode-toolkit>about gen --fetch-license https://enterprise.dejacode.com/api/v2/licenses/ <API KEY> C:\Users\CYL\Desktop\test\tmp\sample.json C:\Users\CYL\Desktop\test\output
```
**Output Directory Structure:**
```
C:\Users\CYL\Desktop\test\output\load\this.ABOUT
C:\Users\CYL\Desktop\test\output\load\apache-2.0.LICENSE
C:\Users\CYL\Desktop\test\output\load\bsd-new.LICENSE
```
**Output this.ABOUT**
```
about_resource: .
name: AboutCode
about_resource_path: .
version: 0.11.0
license_expression: bsd-new AND apache-2.0
license_name: |
    BSD-3-Clause
    Apache License 2.0
license_file: |
    bsd-new.LICENSE
    apache-2.0.LICENSE
license_url: |
    https://enterprise.dejacode.com/urn/?urn=urn:dje:license:bsd-new
    https://enterprise.dejacode.com/urn/?urn=urn:dje:license:apache-2.0
```

The conjunctive (AND) or disjunctive (OR) is defined in the `license_expression` field.

@DennisClark Please feel free to suggest any alternative way or better way to present the data or feel free to close this if you are satisfy with the current output.

**Comment by DennisClark** [comment]
Current solution appears to work fine.
