### ISSUE TITLE
Create install wizard for tool

### ISSUE THREAD

**Issue by ottokruse-sd** [aboutcode-org/aboutcode-toolkit#202]
Create install wizard for AboutCode Tool for Windows, Linux, and Mac environments that will install the tool and all tools it is dependent on.

**Comment by pombredanne** [comment]
@ottokruse-sd can you elaborate what you have in mind there?

Let me fill you in also on the next v3 improvements:
- the only external installation requirement will be a Python installation
- once you download a release archive, you will just run the `about` command and the tool will configure itself on first use if needed

Do you think this would work? or do you something else in mind?

Overall, this is the approach that is used in ScanCode here https://github.com/nexB/scancode-toolkit/releases
You can give it a try on ScanCode to get an idea of how this will work out.

**Comment by chinyeungli** [comment]
@ottokruse-sd @pombredanne I think this can be closed as mentioned the only external installation requirement is Python, and then the tool will configure itself once user run the `about` command.

**Comment by pombredanne** [comment]
Closing as wontfix... @ottokruse-sd feel free to reopen if you feel differently of course
