### ISSUE TITLE
Add configuration file

### ISSUE THREAD

**Issue by ottokruse-sd** [aboutcode-org/aboutcode-toolkit#203]
Add a configuration file in which all parameters needed to run tool can be specified, including locations for all inputs and outputs.  If the user specifies a parameter in the command line it will override the value in the configuration file (otherwise it will just use the values in the configuration file).  A side affect of this will be that the tool can be run anywhere and know where to find all its inputs and outputs in the file system (as it stands they need to have a close coupling).  The configuration file should also specify where the error output is put.

**Comment by pombredanne** [comment]
This makes perfect sense. I guess it should be an ~/.aboutrc file of sorts using the same conventions used in such cases for config files, possibly at multiple levels (in your home directory, then in the about installation directory)

For your comment on location coupling, I created a new ticket: #205

**Comment by chinyeungli** [comment]
This is fixed in #205
