### ISSUE TITLE
Test on appveyor

### ISSUE THREAD

**Issue by chinyeungli** [aboutcode-org/aboutcode-toolkit#208]
as title.

**Comment by chinyeungli** [comment]
@pombredanne do we still want this?

**Comment by chinyeungli** [comment]
@pombredanne do we have an account on appveyor?

**Comment by pombredanne** [comment]
Yes, sorry for the late reply. We still want to have this to ensure that we have no problem on Windows.
And this is already there: https://ci.appveyor.com/project/nexB/aboutcode-toolkit ... you just need to document the link in the README (and same for travis: see how this is done in ScanCode's README.rst)
