### ISSUE TITLE
v2.0.4 requires changes in the about_files references to use the new zip feature

### ISSUE THREAD

**Issue by DennisClark** [aboutcode-org/aboutcode-toolkit#218]
Previously, I have run the about utilities like this: 
genabout.py: 
1. Populated the values in my about_file column in my input .csv to be the codebase path name prefixed by /about_files/ 
2. Created a directory in my project with the project name.  For example: 
/Users/dclark1330/my_workspace/the_project_name/
3. Declared the output_path in my genabout.py command to include the full path with that project name. 
4.  genabout.py then creates an /about_files/ directory inside that project and puts all the output in there. 

genattrib.py: 
Run that using a filter file (note that the about_file column paths all start with "/about_files/") and with the input_path specified as /Users/dclark1330/my_workspace/the_project_name/ .   That works. 

but, if I compress /Users/dclark1330/my_workspace/the_project_name/  to 
/Users/dclark1330/my_workspace/the_project_name.zip  
and then run genattrib.py using that as input, it does not like it, because my filter .csv file doesn't know about "the_project_name".  

So I cannot run this last option (genattrib from a zipped archive) without making some changes. 

If this does not make sense, let me know and I'll create a concrete case using our e2fsprogs example.

**Comment by pombredanne** [comment]
@DennisClark I created some tests and in your scenario, if you zip the about_files directory in a zip, things work exactly as you described, and the path structure inside the zip should just match the path structure you have in your "filter" CSV

**Comment by DennisClark** [comment]
I was able to do a "round-trip" set of genabout and genattrib commands, using the new ability to access a zip file from genattrib, by doing a minor simplification, and it works great.   

Only remaining task is to do that for e2fsprogs and update our example case.  Planning to do that soon.

**Comment by pombredanne** [comment]
@DennisClark if this is fixed, can you close?

**Comment by DennisClark** [comment]
I will address the e2fsprogs example case after some of the other issues that have emerged using archives (zip files) have been resolved.  In the meantime, this specific issue is resolved, so closing.
