### ISSUE TITLE
Collect redistributable sources

### ISSUE THREAD

**Issue by pombredanne** [aboutcode-org/aboutcode-toolkit#22]
Given a directory with ABOUT files OR a csv and directory as an input, I want to collect all the source code archives that have the redistribute flag set , and bundle all these in a zip or tar

**Comment by chinyeungli** [comment]
@pombredanne do we still want to have this feature?

**Comment by pombredanne** [comment]
@chinyeungli I think this is a separate command of feature that may use data collected from an ABOUT inventory. Keep this around for now.

**Comment by chinyeungli** [comment]
The current implementation copy the sources and its directory structure. However, perhaps user doesn't want to expose its project structure, especially the name. We should provide option to only copy the files or copy the files with its directory structure.

**Comment by chinyeungli** [comment]
Should we raise a warning if the copied files already exist in the destination or just simply overwrite it?
I was making the code to raise a warning. However, it acts a bit weird if user has flag redistribution for a directory and a file under this same directory.
For instance,
```
/tmp/a/b/c.java
/tmp/a/
```
If the ABOUT files indicates the `c.java` and the `/a/` should be redistributed, and if the code process the `c.java` first, then the `/tmp/a/` will be created. When it try to copy the `/tmp/a/` to the destination, it will raise warning which is a bit strange.

@pombredanne any comment?

**Comment by pombredanne** [comment]
@chinyeungli You could process a sorted list where the directories are in top-down walk order to avoid these issues?
Alternatively you could avoid issuing warning for pre-existing directories and only issue a warning for files?

**Comment by chinyeungli** [comment]
@pombredanne thanks. I've implemented a similar way about the "top-down walk order", and it's working fine but is kinda complex. Will push the code later once I've everything implemented.

**Comment by pombredanne** [comment]
@chinyeungli your call... in hindsight it may be simpler to only issue warning on existing files? existing directories do not matter as alone they have no content. Of course it depends on how you may the copy (e.g. testing file existence is only possible if you copy file by file)

**Comment by chinyeungli** [comment]
well.. I think existing directores matter if users want to copy src without directory structure.
For instance,
```
/project/java/work/work.ABOUT
/project/java/work/a/a.java
/project/java/work/b.java
/project/c/work/work.ABOUT
/project/java/work/a/a.c
/project/java/work/b.c
```
Assuming the `about_resource` value is `.` meaning it references everything under `work/`
If user copy sources **with directory structure**, then it's fine as the output destination will have
```
/output/project/java/work/work.ABOUT
/output/project/java/work/a/a.java
/output/project/java/work/b.java
/output/project/c/work/work.ABOUT
/output/project/java/work/a/a.c
/output/project/java/work/b.c
```
However, if user doesn't want to include the directory structure and only copy the directories, then an error/warning need to be raised.
Output:
```
/output/work/
```

**Comment by pombredanne** [comment]
I am talking about something different: irrespective of the structure, a directory of itself has no content, hence its pre-existence does not matter. Assuming that you copy files one-by-one, then this when you copy a file and the target file already exists that there should be a warning... with the possibility that there are many warning issued when you copy a whole file tree that already exists e.g. one per file. 
So what about this:
- if you copy a directory, issue a warning IFF the target directory exists. Do not issue a warning if any of its parent directories exist
- if you copy a file, issue a warning IFF the target file exists. Do not issue a warning if any of its parent directories exist

This would alleviate the need to sort things and use a well defined walk order
