### ISSUE TITLE
Explicit input and output args

### ISSUE THREAD

**Issue by pombredanne** [aboutcode-org/aboutcode-toolkit#23]
a -i and -o might be better command lines options than using implicit input and ouputs?

**Comment by tdruez** [comment]
Instead of having a required [Output] arg (current implementation), the default output should be stdout with the possibility to write to a file with the -o options

```
-o, --output=FILE         write result to FILE instead of standard output
```

**Comment by chinyeungli** [comment]
I think this ticket can be closed now.
