### ISSUE TITLE
Make about_file field optional

### ISSUE THREAD

**Issue by jdaguil** [aboutcode-org/aboutcode-toolkit#231]
Make about_file field optional so that you can generate attribution from about files that are detached from a resource location. This is useful in the case where there are multiple components in different locations, and you only want the component to show up in attribution once (vs multiple times)

**Comment by chinyeungli** [comment]
```
Usage: genattrib.py [options] input_path output_path [component_list]
```

The attribution generation doesn't require an input csv file (a.k.a component_list). The tool read information from the ABOUT files and not the input list.
If user does not want to generate attribution from all the ABOUT files, he/she will need to provide a `component_list` to specific which ABOUT files should the tool look at.

@jdaguil can you explain a bit more about what is the issue (See #232 for the multiple components issue)?

**Comment by jdaguil** [comment]
I do not think this issue is needed anymore if a dupe-check component feature is added (See #232 for the multiple components issue). I opened this months ago, so if I recall correctly the flow process that was used that prompted me to enter this issue was in order to generate attribution I first needed the about files. And in order to generate the about files I must have the name, version, and about_file columns in my input csv. So when going through the the about file generation first, any duplicate name-version components will show up in the attribution file since they can come from different about files based on their about_file location. So you can have something like this show up in your attribution file. There is no added value here to have them listed twice in attribution, but they show up twice because they have unique about_file locations.  

**Reachability v 2.2**

This component is licensed under Apple Example Code License.

`Copyright (c) 2010 Apple Inc.`
Full text of Apple Example Code License is available at the end of this document.

**Reachability v 2.2**

This component is licensed under Apple Example Code License.

`Copyright (c) 2010 Apple Inc.`
Full text of Apple Example Code License is available at the end of this document.

I think the thought process at the time was if the about_file field didn't have a value then the component wouldn't be generated, which I don't think is the right way to solve underlying problem. I think we should close in favor of #232.

**Comment by mjherzog** [comment]
So - if I want to document licenses in my codebase with ABOUT files, then there is a logical reason to have multiple copies of a component and yr genattrib file specifies which code location applies for which Deployed Product list. Is the issue from cases where you do not want to specify codebase location? Or is this from cases where we flatten the directory structure for storing  ABOUT files?

**Comment by chinyeungli** [comment]
I think this is fixed as we recently handled the `dedup` things in template level meaning the users can have full control of what will be shown up in the attribution
