### ISSUE TITLE
Generate attribution once even if multiple components exist in a codebase

### ISSUE THREAD

**Issue by jdaguil** [aboutcode-org/aboutcode-toolkit#232]
Ensure we can generate attribution once even if there are multiple components in a codebase. If a component appears in multiple codebase locations, we should be able to generate attribution so that the component only appears once in the attribution file (for unique component version cases).

**Comment by chinyeungli** [comment]
Syntax:

```
Usage: genattrib.py [options] input_path output_path [component_list]
```

Well, I agree and disagree.
**Disagree**
I think the tool should only do the procedure which depends on what user's input.
i.e.
If user want to have all unique component version cases, the user should do the filter and provide genattrib a component_list.

**Agree**
If user doesn't have a inventory list (spreadsheet), the generated attribution will probably confuse the user as multiple components with same version will appear multiple time.

@pombredanne @DennisClark what do you think?

**Comment by DennisClark** [comment]
I guess we need to go back to the problem that @jdaguil  appears to be trying to solve, which is that it is a real pain (and very time-consuming) to do a dupe-check on one's components and remove them from your input csv.  it's especially time-consuming in a customer context where an audit might be dealing with multiple product lines, and you are trying to output attribution for each product line. So given that is the problem we are trying to address: 

I think we need a "summarize-by-component" option on genattrib (you can call it something shorter if you like) that will allow a component to be in one's input multiple times, but only appear once in the output. 

If the right solution means doing both something with the code AND something with one's attribution template file, then that's ok, as long as we have a good example template for people to reference. 

And if i misunderstood the problem, well, never mind !!!

**Comment by chinyeungli** [comment]
@DennisClark thanks for the input. If we plan to do that, I tend to do it internally instead of having user to declare the option because multiple components with same version in the attribution output doesn't make sense anyway.

**Comment by mjherzog** [comment]
I am not in favor of this feature. The input list concept is valid and even ARRIS has figured out how to deal with this. I am not clear how this would be easy for us to do if hard to do manually. We could do better with explaining the reason and usage for the input list

**Comment by chinyeungli** [comment]
FYI, I believe it's not that hard to due with the multiple same components in the code side.
The current procedure in the code side is to collect data from the ABOUT files in a list, and then generate/write the attribution from the list.

If we want the "dedup" feature, we just need to add one step to dedup the list after collected the data.

So, the question here is really do we want this features which users will no longer have control of the output attribution if for some reasons that the user don't care or want to have multiple same components in the attribution doc

**Comment by chinyeungli** [comment]
Actually we handled this in the template level recently. @DennisClark  Can you see if the recent `dedup` template fix this issue?

**Comment by chinyeungli** [comment]
as previous comment, I believe the issue can be handled in the `jinja2`
