### ISSUE TITLE
Use the new License API v2

### ISSUE THREAD

**Issue by tdruez** [aboutcode-org/aboutcode-toolkit#233]
Current DejaCode API is deprecated.

**Comment by tdruez** [comment]
The code was updated to work with the API DejaCode v2 in the v2x_maintenance branch.

Since the username is not required anymore, here's the new usage:

```
genabout.py --extract_license --api_url='https://enterprise.dejacode.com/api/v2/licenses/' --api_key='<api_key>'
```

@chinyeungli please review changes and confirm everything is working fine. Next step is to remove the old API v1 from DejaCode.

**Comment by chinyeungli** [comment]
@tdruez Yes. This is working fine with your update
