### ISSUE TITLE
Generate an ABOUT "Scorecard"

### ISSUE THREAD

**Issue by DennisClark** [aboutcode-org/aboutcode-toolkit#24]
If an engineering organization were to take up using ABOUT in a serious, ongoing way, it probably would be very helpful to provide a tool/utility that would generate a "scorecard" on a target codebase directory. Some of the scorecard points would include:

Percentage/counts of the directories that (1) have no ABOUT info, (2) have some ABOUT info, (3) appear to be fully-documented in ABOUT.

The value of this would be that as new code is checked into a codebase, the scorecard could help determine if it's time to review the ABOUT files.

The scorecard tool might also identify potentially obsolete ABOUT files, where the date (timestamp) on the ABOUT file is older (by a number of days, perhaps parameter-driven) that the file/directory that it describes.

**Comment by chinyeungli** [comment]
@DennisClark This is a good idea. However, there are couple of items that need to discuss.
- (1) have no ABOUT info, (2) have some ABOUT info, (3) appear to be fully-documented in ABOUT.

How do we define an ABOUT file have "some" vs "fully-documented" info?
- User may create an ABOUT file to document the directory(ies), if this is the case, we may not know if user add/remove any new code file in it.
- Are you suggesting we should add a timestamp field for the ABOUT file?

**Comment by DennisClark** [comment]
By "the date (timestamp) on the ABOUT file" I meant the one available on the filesystem where it resides.

**Comment by chinyeungli** [comment]
Similar issue in #10

**Comment by pombredanne** [comment]
Closing this as wontfix. We can track a subset in #110 alright
