### ISSUE TITLE
develop branch: integrate subcommands options 

### ISSUE THREAD

**Issue by chinyeungli** [aboutcode-org/aboutcode-toolkit#242]
All the subcommands options such as `--overwrite`, `--mapping`, `--extract_license` etc. have not been integrated yet.

**Comment by chinyeungli** [comment]
```
  --verbosity=VERBOSITY
                        Print more or fewer verbose messages while processing ABOUT files
                        0 - Do not print any warning or error messages, just a total count (default)
                        1 - Print error messages
                        2 - Print error and warning messages
```

The `0` option will not be integrated as we already have the `-q, --quiet` option

**Comment by chinyeungli** [comment]
Perhaps we only need one option which is print error messages only for this instead of having user to set the 'number'.
For instance,
we already have the `-q` option for the `about`
if user set `-q` option, we don't need to print anything
if user don't set `-q` option, we should print everything (errors and warnings)

so it left with one scenario that the user don't set `-q` but want to print the error message only.

Note that all the errors and warning should still be kept in the error.log. The above option is just for printing to the stdout.

**Comment by chinyeungli** [comment]
We need to adapt the new verbosity approach for printing the following:

```
# modeled after the logging levels
CRITICAL = 50
ERROR = 40
WARNING = 30
INFO = 20
DEBUG = 10
NOTSET = 0
```

**Comment by chinyeungli** [comment]
All the option for `about.py` have been integrated.

**Comment by chinyeungli** [comment]
```
  --action=ACTION       Handle different behaviors if ABOUT files already existed
                        0 - Do nothing if ABOUT file existed (default)
                        1 - Overwrites the current ABOUT field value if existed
                        2 - Keep the current field value and only add the "new" field and field value
                        3 - Replace the ABOUT file with the current generation
```

Do we really need action 2 and 3? @DennisClark I would like to have your input.

**Comment by pombredanne** [comment]
@chinyeungli: I think you can simplify a lot. IMHO we should not EVEN have these actions options at all.
we should always regen things as new correct data. Anything else is likely to create confusion, and it does confuse me

**Comment by DennisClark** [comment]
@chinyeungli    After a bit of thought, I am inclined to agree with @pombredanne   that we should "always regen things as new correct data"  and that the options are not necessary.

**Comment by chinyeungli** [comment]
okay, thanks for the input.

**Comment by chinyeungli** [comment]
I think I've integrated all the `will use` options to the code.
