### ISSUE TITLE
JSON template correction

### ISSUE THREAD

**Issue by chinyeungli** [aboutcode-org/aboutcode-toolkit#253]
1.  JSON (at least parsers, et al) do not support “newlines” (real ones) in the values associated with parameters, so instead of having an actual newline character, a “\n”  is required instead (at least this is what I have found so far). Your JSON output had newlines instead of the escaped characters.
2.  Both sides of the parameter:value pair need to be quoted. In the entries array of the JSON output provided, the values were not quoted, only the parameters.

**Comment by pombredanne** [comment]
This is fine to fix for sure, but this is a short term solution... The proper support for JSON is the devel branch.

**Comment by pombredanne** [comment]
@chinyeungli will you update the JSON template as a hot fix in the master branch? or ?

**Comment by chinyeungli** [comment]
Use http://jsonlint.com/ or http://www.jsoneditoronline.org/ to check for valid JSON file.
