### ISSUE TITLE
Multi dje_license_key is not yet supported

### ISSUE THREAD

**Issue by chinyeungli** [aboutcode-org/aboutcode-toolkit#260]

**Comment by JonoYang** [comment]
@chinyeungli What is the status on this issue? I would like to create attributions for components whose license expression that have multiple keys.

**Comment by chinyeungli** [comment]
@JonoYang Sorry, there is not much status to say here as I'm deep in with other project.. I will come  back to work on this when I get a break.

**Comment by chinyeungli** [comment]
See #275
