### ISSUE TITLE
Add support for multiple license keys

### ISSUE THREAD

**Issue by chinyeungli** [aboutcode-org/aboutcode-toolkit#263]

**Comment by chinyeungli** [comment]
The current model has the following

```
('license_name', StringField(capture=True)),
...
('dje_license_key', SingleLineField(capture=True)),
```

which shows no multi-license can be generated at this moment.

**Comment by chinyeungli** [comment]
We are having problem to create a dictionary list which have license short name as a key and license context as a value to pass to the template for generation.

For instance,

```
about_resource: jsch-0.1.52.jar
name: Jsch
version: v 0.1.52
license_name: |
    BSD-Modified
    Apache License 2.0
    MIT License
    Public Domain
license_file: |
    apache-2.0.LICENSE
    bsd-new.LICENSE
    public-domain.LICENSE
    mit.LICENSE
license_url: |
    https://enterprise.dejacode.com/urn/?urn=urn:dje:license:bsd-new
    https://enterprise.dejacode.com/urn/?urn=urn:dje:license:apache-2.0
    https://enterprise.dejacode.com/urn/?urn=urn:dje:license:mit
    https://enterprise.dejacode.com/urn/?urn=urn:dje:license:public-domain
copyright: Copyright (c) Atsuhiko Yamanaka
dje_license_key: |
    bsd-new
    apache-2.0
    mit
    public-domain
confirmed_license: BSD-Modified
```

When the tool look at the above ABOUT file, it cannot associate the 'BSD Modified' with 'bsd-new.LICENSE' or 'Apache 2.0' with 'apache-2.0.LICENSE'

The reason we need the short name is because  it looks better and the short name is used to identify COMMON_LICENSES listed in the licenses.py

**Comment by chinyeungli** [comment]
We are not supporting to show license short name by default.
Fixed in
https://github.com/dejacode/about-code-tool/commit/1e5c2b2c501d4b52c3d6576d7764237fc90a90e2

**Comment by pombredanne** [comment]
@chinyeungli Is this is really closed? We should IMHO add support for SPDX license expressions and not multiple keys. And the multiple text fields that are like parallel lists without being lists nor dicts is not a the best way. Are we sure this is really closed?

**Comment by chinyeungli** [comment]
For the multiple license texts, I ran some actual tests and it's working, but I should have added test code for it.
For the support of SPDX license, perhaps another ticket?

**Comment by pombredanne** [comment]
It can stay this same ticket I guess: SPDX-like expressions is really about multiple license keys, but I am fine either way

**Comment by chinyeungli** [comment]
The current code use yaml `newline` for multiple lines/multiple licenses support.
For instance,
```
about_resource: .
name: test
license: |
    x11
    mit
    public-domain
    bsd-simplified
```

I've entered #275 for support of license expression.
We will not support license expression in version 3.
Closing this.
