### ISSUE TITLE
Improve genabout.py to fail immediately from invalid combination of api_url and api_key values

### ISSUE THREAD

**Issue by DennisClark** [aboutcode-org/aboutcode-toolkit#265]
If I run genabout.py with an invalid combination of api_url and api_key values, it hangs up completely (requiring me to kill the process from the command line) rather than failing outright.  It would be much better if it failed immediately and gave me an error message on the terminal.

**Comment by chinyeungli** [comment]
This fixed hasn't been merged into the master branch

**Comment by chinyeungli** [comment]
This has already been handled.
