### ISSUE TITLE
Generate attribution from zip file with component list not working

### ISSUE THREAD

**Issue by chinyeungli** [aboutcode-org/aboutcode-toolkit#276]
Generate attribution with component list from a directory work fine.
However, if user zips the `about_files` directory to the `about_files.zip` and run attribution from there, it will not work.
The code will create a directory named `about_files`, the name of the zip file, under some tmp directory and extract the `about_files.zip` content to that directory and run from there
for instance,
```
/home/user/tmp/xxxbxbxbxx/about_files/about_files/test.h
```

The input has the `/about_files/test.h` as the about file path, so when running the attribution from the created tmp directory, `/home/user/tmp/xxxbxbxbxx/about_files/`, it will look for `/about_files/about_files/test.h` and that's why it is not working (because of the extra `/about_files`)

@DennisClark I would like to know if this also happens to MacOS or is it a windows issue?

**Comment by DennisClark** [comment]
Hi @chinyeungli  -- I am afraid that I don't completely understand what my test data should look like.  Based on your description, the data is what I normally do: 
* Run genabout to write everything under an /about_files/ directory. 
* Compress that to about_files.zip
* Use about_files.zip as input when I run genattrib. 

Are you saying that if I had another /about_files/ directory under my top-level /about_files/ directory that it would fail?  or some other condition?

**Comment by chinyeungli** [comment]
@DennisClark Yes.
For instance, your `non-zipped` input is something like
```
/home/User/abc/about_files/
```
When you zip that directory and use it for attribution generation, the tool will create a `about_files` directory under a tmp location such as
```
/home/User/tmp/xxxxxaaaaa/about_files/
```
and then extract the content under it and become
```
/home/User/tmp/xxxxxaaaaa/about_files/about_files/
```
It is nothing wrong with your test data, I will see what can I do in the code side. Thanks for looking at it.

**Comment by chinyeungli** [comment]
The code keeps the last segment of the `base_loc` to become the first segment of the returned path in the `get_relative_path` function
i.e.
the `base_loc` is 
```
/home/User/tmp/xxxxxaaaaa/about_files/
```
and the `about_file_path` from the input begins with `about_files`, so when keeping the last segment from the `base_loc` and join the about_file_path, it will has 2 `about_files` segments in the returned path and this will not match with the `about_file_path` in the component list and causing errors.

In another example, if user has the following about_file_path for input:
```
/about_files/test.c
```
and generate about file at
```
/home/User/abc/about_files/test.c.ABOUT
```

Then, if the user zip it at the `about_files/` level under the named 'metadata.zip', the code will extract this zip file in a tmp location such as `/home/User/tmp/xxxxxaaaaa/metadata/about_files/test.c.ABOUT` with `base_loc` = ``/home/User/tmp/xxxxxaaaaa/metadata/`

The previous code will use the last segment of the `base_loc` as the root of the returned path, the tool will try to match the `/metadata/about_files/test.c.ABOUT` with the `about_file_path` from the input component list in genattrib, and it will throw error because there is no `/metadata/about_files/test.c.ABOUT` about_file_path in the component list.

**Comment by chinyeungli** [comment]
This has been fixed.
