### ISSUE TITLE
Output inventories and ABOUT data as JSON

### ISSUE THREAD

**Issue by pombredanne** [aboutcode-org/aboutcode-toolkit#277]
Beside the YAML and CSV formats, we should have support for a proper JSON output  
Note that this would likely need to integrate ScanCode models first and then use ScanCode features for JSON.

**Comment by chinyeungli** [comment]
In the develop branch,
`gen`
We generate YAML format's ABOUT files from a CSV/JSON input
`inventory`
We generate an inventory in CSV/JSON format from the ABOUT files

so we already have support for JSON as an input and output
