### ISSUE TITLE
The `about_file_path` for the "usual" input for `gen` should be `about_resource_path`

### ISSUE THREAD

**Issue by chinyeungli** [aboutcode-org/aboutcode-toolkit#289]
The current design is to name the `Resource` column as `about_file_path` and the the tool will generate the corresponding .ABOUT file next to the resource.
However, the "real" meaning for the "Resource" should be `about_resource_path` instead of `about_file_path`.

**Comment by pombredanne** [comment]
The code has changed since and this ticket is now invalid.
