### ISSUE TITLE
Add support for python3 in the "configure" script

### ISSUE THREAD

**Issue by tdruez** [aboutcode-org/aboutcode-toolkit#291]
As a requirement to complete https://github.com/nexB/aboutcode-toolkit/issues/280#issuecomment-333524722

The current version of the `configure.py` code breaks in many places when trying to run it with python3.6.

**Comment by supragya** [comment]
For me, the error report was:
`https://gist.github.com/supragya/51e589231c8c3cc0e5119c405bfa83f4`

If this is the case, the guess is the bug is in distribution packages itself.
`https://bugs.launchpad.net/ubuntu/+source/python3.6/+bug/1631367`

I may very well be going in wrong direction. Please check :-)

**Comment by pombredanne** [comment]
@supragya Thanks for chiming in! 
Can you tell me which steps you took to get this https://gist.github.com/supragya/51e589231c8c3cc0e5119c405bfa83f4 ?
e.g. which Python version? which OS? which command did you run?
For instance this https://github.com/nexB/aboutcode-toolkit/blob/develop/configure#L30 would for a start force Python 2.7... so can you tell which changes you did and were?

**Comment by pombredanne** [comment]
... because I doubt there are bugs elsewhere except in our code at first!

**Comment by tdruez** [comment]
@pombredanne After changing https://github.com/nexB/aboutcode-toolkit/issues/291#issuecomment-338739101 to `python3.6` and running `./configure`
```
Traceback (most recent call last):
  File "/Volumes/nexB/aboutcode-toolkit/etc/configure.py", line 380, in <module>
    activate(root_dir)
  File "/Volumes/nexB/aboutcode-toolkit/etc/configure.py", line 206, in activate
    with open(activate_this) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Volumes/nexB/aboutcode-toolkit/bin/activate_this.py'
```

**Comment by supragya** [comment]
@pombredanne My procedure on Ubuntu 17.04 ZZ was:
`sudo apt-get install python3.6-minimal` and hence the error after changing https://github.com/nexB/aboutcode-toolkit/blob/develop/configure#L30 to python3.6 was given. However as @tdruez did not have that problem, I guess it was system specific.

**Comment by pombredanne** [comment]
@supragya not sure this is system specific: one thing is that I think in 3.6 virtualenv is baked in Python.
So the first change that may be required is to change the way venv are created in configure.py
Also I doubt that using the `python-minimal` may be enough.... What does it contain?

**Comment by pombredanne** [comment]
@tdruez Thanks. I guess the mechanics of virtualenv programmatic activation has changed in 3.6. So this is the first thing to dig in
