### ISSUE TITLE
INFO reported in `inventory` but not in `check`

### ISSUE THREAD

**Issue by tdruez** [aboutcode-org/aboutcode-toolkit#295]
```
about-code inventory . inventory.csv
Running attributecode version 3.0.0.dev5
Collecting inventory from: my_directory/ and writing output to: inventory.csv
INFO: _pyahocorasick.ABOUT: Field dje_license is not a supported field and is ignored.
```
This `INFO` is relevant and I'm expecting the same data while running `check` on the same directory, but instead `no errors is found`.
```
about-code check .
Running attributecode version 3.0.0.dev5
Checking ABOUT files...
No error is found.
```

**Comment by chinyeungli** [comment]
The `check` command is designed to check for problematic_errors. 
https://github.com/nexB/aboutcode-toolkit/blob/develop/src/attributecode/cmd.py#L232
https://github.com/nexB/aboutcode-toolkit/blob/develop/src/attributecode/cmd.py#L67

Do you suggest I should raise the `not supported field` to become a `WARNING` error?

If that's the case, all the custom fields such as "Notes", "Internal Comments", "Deploy" etc... (I'm making these up) will throw `WARNING` error?

**Comment by tdruez** [comment]
> Do you suggest I should raise the not supported field to become a WARNING error?

Not exactly, I'm suggesting that we should have the option to get those `INFO` with the `check` command. A verbosity option for example.

**Comment by chinyeungli** [comment]
okay.. will work on that

**Comment by tdruez** [comment]
New `--show-all` works fine. Thanks!
