### ISSUE TITLE
JSON object must be str, not 'bytes' error when using python3

### ISSUE THREAD

**Issue by chinyeungli** [aboutcode-org/aboutcode-toolkit#297]
```
ERROR: the JSON object must be str, not 'bytes'
```
I have the above error when using Python 3 in `gen` to fetch license.

After some investigation, it seems the problem is at 
https://github.com/nexB/aboutcode-toolkit/blob/280-python3-cleanup/src/attributecode/api.py#L66
```
response_content = response.read()
```
The fix is likely this: https://stackoverflow.com/a/32250010
i.e.
```
response_content = response.read().decode('utf-8')
```

However, I'll like to have your input on this.

**Comment by tdruez** [comment]
@chinyeungli before jumping onto a fix, could you add a simple unit test that expose the issue?

**Comment by chinyeungli** [comment]
will do
