### ISSUE TITLE
File does not exist error is annoying

### ISSUE THREAD

**Issue by chinyeungli** [aboutcode-org/aboutcode-toolkit#300]
I get a whole bunch of ERROR messages of this type, even though they don't stop the process from completing: 

"ERROR: The reference file : home/user/project/file/abc.java does not exist" 

And my initial reaction, as someone using the tool, is "so what? why are you looking for that? since when is about/gen a scanning tool?" The messages (there were lots of them) are annoying, and they don't make any sense to me as something useful. How can I stop these messages?

**Comment by chinyeungli** [comment]
@pombredanne what have designed the code should check the existence of about reference file. However, from the actual user's feedback @DennisClark . It seems this feature is not welcome and causing confusion. Should we remove this?

**Comment by pombredanne** [comment]
@chinyeungli which command do you run to reproduce?

**Comment by DennisClark** [comment]
If you run any  `./about gen`  it actually looks for the code files referenced in your input file.

**Comment by pombredanne** [comment]
@DennisClark thanks. Ideally this should only be reported with a `--verbose` option and or some option that request this check to be made.

**Comment by chinyeungli** [comment]
Thanks for the input, I will work on it

**Comment by chinyeungli** [comment]
The `gen` should have been handled. Need to check the behavior for `inventory` and `attrib` next.

**Comment by DennisClark** [comment]
@chinyeungli   Testing with the latest develop branch went fine.  Problem resolved, thanks.
