### ISSUE TITLE
Track SHA1s for all files in a code folder

### ISSUE THREAD

**Issue by chinyeungli** [aboutcode-org/aboutcode-toolkit#303]
Plan:
The AboutCode tool should collect all the sha1's in a directory and put them into a list. 
As a result, when a user uses AboutCode  next time, AboutCode will collect all the sha1's again and compare with this list to track what's been changed.

Related #107 

@pombredanne is this something that we still want to have?

**Comment by pombredanne** [comment]
I think this will be supported by the upcoming deltacode by @majurg  instead and should not exist in multiple places OR should be a shared library
