### ISSUE TITLE
Make `--fetch-license` its own subcommand instead of a gen option

### ISSUE THREAD

**Issue by chinyeungli** [aboutcode-org/aboutcode-toolkit#308]
We can even fetch ABOUT files, notices etc... from dejacode

**Comment by mjherzog** [comment]
We need to be clear about any ABC Tookit functions/features that require a DejaCode subscription - these always need to be optional.

**Comment by chinyeungli** [comment]
One of the features for having `--fetch-license` as an option from `gen` is the tool can update the `license_name` and `license_file` fields in the ABOUT files.

if we make the `--fetch-license` as a subcommand, the tool can fetch and create <LICENSE>.LICENSE with no problem, but the ABOUT file may not have a "proper" reference to reference the fetched license. For instance, the ABOUT file may only have the `license_expression` field but does not have the `license_name` or `license_file` field.

**Comment by pombredanne** [comment]
The --fetch-license option should be a separate sub-command that fetches and stores license texts **and data** in a reference directory that can then be used at ABOUT generation time.
It can use the same approach as ScanCode to store license data in YAML files. Then these licenses (and any other licenses) can be referenced when generating ABOUT files.
I am scheduling this for 4.0

**Comment by mjherzog** [comment]
Does this mean an option to pull license text from the ScanCode license repo?

**Comment by pombredanne** [comment]
@mjherzog for instance yes.

**Comment by pombredanne** [comment]
This is fixed in https://github.com/nexB/aboutcode-toolkit/tree/361-make-transform-work branch
