### ISSUE TITLE
'about_file_path" does not support spaces

### ISSUE THREAD

**Issue by chinyeungli** [aboutcode-org/aboutcode-toolkit#310]
This is a bug. The 'about_file_path' should have space support

**Comment by chinyeungli** [comment]
From the spec
```
    From spec :
        A file name can contain only these US-ASCII characters:
        - digits from 0 to 9
        - uppercase and lowercase letters from A to Z
        - the _ underscore, - dash and . period signs.
```

@pombredanne should we support spaces in filename?

**Comment by chinyeungli** [comment]
@pombredanne I think supporting spaces in filename is appreciated. Let me know if you disagree.

**Comment by chinyeungli** [comment]
Note that we have tests which treat space as invalid character

`def test_check_file_names_with_invalid_chars_return_errors` and `def test_invalid_chars_with_space(self):`

**Comment by pombredanne** [comment]
Fixed and merged in develop.
