### ISSUE TITLE
[suggestion] Optional field for patents

### ISSUE THREAD

**Issue by maxbrito** [aboutcode-org/aboutcode-toolkit#316]
Some ABOUT files are covered by specific patents. Perhaps we can have a field dedicated to list them?

A specific case would be SZIP: https://support.hdfgroup.org/doc_resource/SZIP/Commercial_szip.html that is/was covered by patents in the US.

Perhaps possible to have optional fields such as:
```
patent: US Patent 5448642
patent: US Patent 5687255
patent: US Patent 5822457
```
I'm not an expert on patents, so wouldn't really know in detail how we would list patents for EU, UK and other lands. Albeit I'm sure we could likely find a way to keep this simple and intuitive.

In either case would help the tools/humans to clearly identify the existence of patents for a specific component.

Many thanks.

**Comment by chinyeungli** [comment]
The tool has the ability to create custom field in ABOUT files (i.e `patent` in the case).
See https://github.com/nexB/aboutcode-toolkit/blob/develop/src/attributecode/mapping.config

We think the patent part should be custom - esp. since it is so dependent on domain and country

**Comment by maxbrito** [comment]
Makes perfect sense. Let's close this topic then.
