### ISSUE TITLE
Improve documentation of `about gen`

### ISSUE THREAD

**Issue by steven-esser** [aboutcode-org/aboutcode-toolkit#317]
Myself and others (https://github.com/nexB/aboutcode-manager/issues/238) have run into some confusion when trying to generate ABOUT files from an inventory file. 

Specifically, the default `MAPPING.CONFIG` values and file location were a mystery to me until consulting with @DennisClark. 

We should probably add some more documentation on both:
* what `about gen` defaults to when NOT passing `--mapping`
* the default location that AboutCode looks for the `MAPPING.CONFIG` file when `--mapping` is passed as an arg

https://github.com/nexB/aboutcode-toolkit/issues/305 Will go a long way to making this more clear as well.

**Comment by chinyeungli** [comment]
@majurg Please see if the update make it more clear, or otherwise, please feel free to suggest for wording improvement.

**Comment by steven-esser** [comment]
Will take a look

**Comment by steven-esser** [comment]
@chinyeungli Your additions and changes look good and clear up the issues I was having. You can close this.
