### ISSUE TITLE
No multiple occurrences keys support

### ISSUE THREAD

**Issue by chinyeungli** [aboutcode-org/aboutcode-toolkit#324]
From the spec,
```
The field order does not matter with the following exception: multiple occurrences of a field name are possible and must be interpreted such that only the last occurrence is considered as the value for this field name. Previous occurrences of the same field name must be treated as ignored fields.
```
I think multiple occurrences should not be supported as it will potentially create confusion.

The tool currently don't take multiple occurrence keys from input csv  for the `gen` process, but take multiple occurrence keys from input ABOUT file for `inventory` process.

**Comment by chinyeungli** [comment]
@pombredanne and @DennisClark I'll like to have your input on about whether or not we should have multiple occurrence keys supported.

**Comment by DennisClark** [comment]
It does not seem to me something that we really need.
