### ISSUE TITLE
Question on BooleanField value

### ISSUE THREAD

**Issue by chinyeungli** [aboutcode-org/aboutcode-toolkit#327]
Following are the keys that only take Boolean value:
```
            ('redistribute', BooleanField()),
            ('attribute', BooleanField()),
            ('track_change', BooleanField()),
            ('modified', BooleanField()),
```

My question is should this be restricted? For instance, some users may want to have a `x` instead of `Yes` to represent the True condition and a `blank value` instead of `No` to represent the False value.

@DennisClark and @pombredanne input are welcome

**Comment by DennisClark** [comment]
I think it's a good idea to support `x` and `blank value`  for BooleanField; in fact, ideally some or all of the following should be supported: 

Yes: True, T, Yes, Y, x
No: False, F, No, N, blank

**Comment by chinyeungli** [comment]
Bugs:
In the `gen` process, the current code will only generate 'yes' value for: **True, T, Yes, Y**
However, if user has **False, F, No, N** in the boolean field, the tool will not have this field generated in the ABOUT file.

In the `inventory` process, the following boolean value seems been ignored: **yes, no**, only **Y, N** works

**Comment by mjherzog** [comment]
I recommend one set of values only for simplicity and clarity with blank allowed. The ABOUT "specification" says "Flag fields have a "true" or "false" value. True, T, Yes or Y must be interpreted as "true" in any case combination. False, F, No or N must be interpreted as "false" in any case combination." so we should revisit that also.

**Comment by chinyeungli** [comment]
@mjherzog 
> I recommend one set of values only for simplicity and clarity with blank allowed.

Do you mean the tool should only show the True Boolean value whenever user uses T, True, Yes, Y, while and the tool will not show the False Boolean value in the output?

For instance,
If the input CSV has modified = N and attribute = Y, the generated ABOUT file will only has attribute: yes and the modified key will not be created.

Same behavior the other way around. If the ABOUT file has modified = N and attribute = Y, the generated inventory (csv or json) file will only has attribute: yes and the modified key will not be created (or blank in the CSV case)

**Comment by chinyeungli** [comment]
@DennisClark @mjherzog please see the above notes if that make sense to you, or do we still want to support `x` and `true` etc..

**Comment by chinyeungli** [comment]
>Do you mean the tool should only show the True Boolean value whenever user uses T, True, Yes, Y, while and the tool will not show the False Boolean value in the output?

After thinking again, I think if users put a "No" or false value in the boolean field, they mean to put it there and the generated ABOUT files or inventory should contains the "False" value.

**Comment by chinyeungli** [comment]
@DennisClark and @mjherzog 
The above fixes add support for 'x' as a True value for boolean field, but in the end, the tool will convert all the "True" to "yes" and all the "False" to "no" in the output (either in the generated ABOUT file or the inventory file)
Note that in the `gen` process, if a boolean field, let say the "modified" field, is empty, the boolean field will not be shown in the generated ABOUT file.

For instance,
```
about_file_path, about_resource, name, modified, track_changes
/input/project/about3.ABOUT, test3.c, test3.c, x, no
```
will gives
```
about_resource: test3.c
about_resource_path: test3.c
modified: yes
name: test3.c
track_changes: no
```

and
```
about_file_path, about_resource, name, modified, track_changes
/input/project/about3.ABOUT, test3.c, test3.c, , no
```
will gives
```
about_resource: test3.c
about_resource_path: test3.c
name: test3.c
track_changes: no
```
