### ISSUE TITLE
Enhance the gen --fetch-license option to generate license URL's

### ISSUE THREAD

**Issue by DennisClark** [aboutcode-org/aboutcode-toolkit#330]
When I run `gen` to generate ABOUT files, I use the --fetch-license option, which works fine when I provide the a value in the license_expression column (or map to it), and it validates the license_expression values that I provide and generates the .LICENSE files, and stores the license_expression and .LICENSE file names in the .ABOUT files that get generated -- so far so good. 

However, for the reports that I generate, I also need the URL to each license in my license library.  Right now I do that with by providing values in the license_url column.  Those are easy enough to construct in my input csv by using an Excel CONCATENATE formula, but that only works well when the license_expression references exactly one license key; otherwise I need to do that task manually.  It would be really helpful if the --fetch-license option could capture and save each license_url when it validates the license using the relevant part of api root url that I provide.   Here is an example (somewhat obscured) of the kind of output I would like to see in the .ABOUT file: 

```
license_expression: apache-2.0 AND oasis-ws-security-spec AND w3c AND ws-policy-specification
license_name: |
    Apache License 2.0
    Oasis WS Security Specification License
    W3C Software Notice and License
    WS-Policy Specification
license_file: |
    apache-2.0.LICENSE
    oasis-ws-security-spec.LICENSE
    w3c.LICENSE
    ws-policy-specification.LICENSE
license_url: |
    http://{{my-license-library}}/urn/urn:dje:license:apache-2.0
    http://{{my-license-library}}/urn/urn:dje:license:oasis-ws-security-spec
    http://{{my-license-library}}/urn/urn:dje:license:w3c
    http://{{my-license-library}}/urn/urn:dje:license:ws-policy-specification
```

**Comment by chinyeungli** [comment]
When you generating the ABOUT files, if your input has the `license_expression` provided, the `license_url` will be generated for row that don't have a license_url's value.
For instance, if your input CSV has the following content:
1.
```
about_file_path,name,license_expression
/test/sample.c, sample.c, apache-2.0 AND oasis-ws-security-spec AND w3c AND ws-policy-specification
```
The ABOUT files will look like:
```
about_resource: sample.c
name: sample.c
about_resource_path: sample.c
license_expression: apache-2.0 AND oasis-ws-security-spec AND w3c AND ws-policy-specification
license_name: |
    Apache License 2.0
    Oasis WS Security Specification License
    W3C Software Notice and License
    WS-Policy Specification
license_file: |
    apache-2.0.LICENSE
    oasis-ws-security-spec.LICENSE
    w3c.LICENSE
    ws-policy-specification.LICENSE
license_url: |
    https://{{my-license-library}}/urn/?urn=urn:dje:license:apache-2.0
    https://{{my-license-library}}/urn/?urn=urn:dje:license:oasis-ws-security-spec
    https://{{my-license-library}}/urn/?urn=urn:dje:license:w3c
    https://{{my-license-library}}/urn/?urn=urn:dje:license:ws-policy-specification
```
2,
```
about_file_path,name,license_expression,license_url
/test/sample-1.c, sample-1.c, public-domain,http://www.example.com
```
The ABOUT files will look like:
```
about_resource: samlpe-1.c
name: sample-1.c
about_resource_path: sample-1.c
license_expression: public-domain
license_name: Public Domain
license_file: public-domain.LICENSE
license_url: http://www.example.com
```

**Comment by DennisClark** [comment]
Tested `gen` successfully without providing `license_url` values in the input file.  The generated .ABOUT files contain the correct URL values, even for complex license expressions.  Works great, so I believe that I can close this issue.
