### ISSUE TITLE
How to make the Title of a generated Attribution file a variable

### ISSUE THREAD

**Issue by DennisClark** [aboutcode-org/aboutcode-toolkit#332]
It is very clear how `attrib` uses a template file to determine the variable values for each of the detail rows.  But is there a good way to specify variables for the header text of the attribution file to be created?  For example, I have an attribution template that starts like this: 
```
<!doctype html>
<html>
    <head>
	<style type="text/css">
		div.additional-license-text-list {display:block}
		body {font-family: Helvetica, Arial, sans-serif;}
		pre {white-space: pre-wrap;}
		li {font-weight: bold;}
		#header {font-family: Helvetica; font-style:italic}
	</style>
        <title>Product 101 - Open Source Software Information</title>
    </head>

    <body>
        <h1>Product 101 - Open Source Software Information</h1>
	<pre id="header">
Some standard text...

{{The template details... }} 
```

I would like to be able to substitute something for "Product 101 - Open Source Software Information" so that the Title itself is a runtime variable.  Is there a recommended way to do that?

**Comment by chinyeungli** [comment]
I think this need to be handled in the code side.
In order to get the title in runtime, I think we need to implement a new option such as `--attrib_title`.
For instance,
```
about attrib --attrib_title "Product 101" [input ABOUT files] [output]
```
so that the tool get the user declared title as a variable and pass it to the template.

@DennisClark @pombredanne @mjherzog 
How does this sound?
I'll like to get more input on this.

**Comment by DennisClark** [comment]
@chinyeungli   Your suggestion is a good one.  We just need to have a standard name (label) for the variable field in the actual template text.  `attrib_title` would work just fine.  I will be happy to test it if you make the code enhancement.

**Comment by chinyeungli** [comment]
we should avoid using `_` underscore in a command line option
Instead use a `-` dash consistently.
As for the `--attrib-title` ,  `--title` may be enough

**Comment by chinyeungli** [comment]
PO: we should likely consider a more generic way to pass variables and not add one new option for each variable

**Comment by chinyeungli** [comment]
@DennisClark @pombredanne suggestion/feedback are welcome

**Comment by chinyeungli** [comment]
Perhaps we can doing something like what the `--mapping` is doing?
i.e. have a file store the key/value pair 
```
title: Product 101
```
etc

**Comment by pombredanne** [comment]
> Perhaps we can doing something like what the --mapping is doing? i.e. have a file store the key/value pair

Yes, that could be a better approach BUT this defeats the purpose to enter per-run specific options as command line options as this would require to create a file.

We need something that is both a command line option and somewhat generic

**Comment by chinyeungli** [comment]
Another approach:
have an option called `--variables` with a list?
For instance,
```
attrib --variable [title='Attribution Notice', header='Product 101'] ...
```

**Comment by pombredanne** [comment]
@chinyeungli `about attrib --variable [title='Attribution Notice', header='Product 101'] ...` would not be very usable and would mix in Python syntax with the command line which would not be great.

Instead we could have an option with multiple entries, where each entry is a name/value pair e.g. something like:
 
`about attrib --variable title="Attribution Notice" --variable header=Product-v1`


And the name `variable` is not very explicit: we should find a better name? Any other suggestion?

**Comment by DennisClark** [comment]
How about `--vartext` ?   so we might have

`about attrib --vartext title="Ringtail Attribution Notice" --vartext header="Ringtail 3.6" `   

that might work.

**Comment by DennisClark** [comment]
Confirmed the `--vartext` feature using the current (2018-09-10) develop branch.  Also corrected the example provided in USAGE.rst.  I think this one is good to go.

**Comment by chinyeungli** [comment]
@DennisClark thanks for checking this out.
