### ISSUE TITLE
Question about filtering the data selected by the attrib process

### ISSUE THREAD

**Issue by DennisClark** [aboutcode-org/aboutcode-toolkit#333]
I have an attribution template which has some code that works great to eliminate duplicates from the output file: 

```
        <div class="oss-table-of-contents">
            {% set glob={} %}
            {% for about_object in abouts | sort(attribute='name.value') %}
                {% set name_version = about_object.name.value + about_object.version.value %}
                {% if glob[name_version] %}
                    {# PASS #}
                {% else %}
                    <p><a href="#component_{{ loop.index0 }}">{{ about_object.name.value }}{% if about_object.version.value %}  - Version  {{ about_object.version.value }}{% endif %}</a></p>
                    {% set about_dict = glob.update({name_version: True}) %}
                {% endif %}
            {% endfor %}
        </div>
```

I would also like to filter by an additional data element, which we can call `product101` as an example. This element either has an `x` to indicate that the component is deployed on product101 or it has a null value if not.   Here are my questions: 

* what's the right syntax to append an OR clause to the `    {% if glob[name_version] %}  `  line that also checks the value of my product101 element? 
* is it ok to have such an element be `x` or null, or does it always need a value such as `Y` or `N` ? 
* does the element need to be in my .ABOUT files, or can it simply be a column in my input control file?

**Comment by chinyeungli** [comment]
> what's the right syntax to append an OR clause to the {% if glob[name_version] %} line that also checks the value of my product101 element?

It should be something like 
```
{% if glob[name_version] or about_object.product101.value %}
```
> is it ok to have such an element be x or null, or does it always need a value such as Y or N ?

It is okay to have 'x' or 'null' as this is a custom column and will be treated as String field.

> does the element need to be in my .ABOUT files, or can it simply be a column in my input control file?

The element needs to be in the .ABOUT files. `attrib` process get all the information from .ABOUT files.

**Comment by DennisClark** [comment]
@chinyeungli    Thanks, I got it to work, although I flipped the logic around a bit: 

```
                {% if glob[name_version] or (about_object.product101.value = '') %}
                    {# PASS #}
```
successfully leaves out the rows where "product101" is null rather than "x". 

Since my questions are all answered, and I have verified them in my own testing, I'm closing this issue.
