### ISSUE TITLE
Should we support author file tag?

### ISSUE THREAD

**Issue by licodeli** [aboutcode-org/aboutcode-toolkit#336]
This ticket is just for discussion. Please close if needed. In some cases, authors are a long list,  and some times, authors even have popularity etc. The author file may help. Please refer to the attachments.

**Comment by licodeli** [comment]
[Django.AUTHORS.txt](https://github.com/nexB/aboutcode-toolkit/files/2212180/Django.AUTHORS.txt)

**Comment by chinyeungli** [comment]
@pombredanne any feedback on adding a `author_file` field?
