### ISSUE TITLE
The about check command does not make enough checks

### ISSUE THREAD

**Issue by pombredanne** [aboutcode-org/aboutcode-toolkit#337]
The `about check` command could do more checks: it does not check if the license expressions syntax is correct or if the licenses keys are valid. It also does not check that some important field are present such as `license_expression`

**Comment by chinyeungli** [comment]
@pombredanne in terms of `important` field, `license_expression` is not a required field and, therefore, it should not be checked for the existence of the `license_expression` field. OR should we make this field required?

**Comment by chinyeungli** [comment]
If we need to verify the correctness of the license keys, we need user to provide valid api key to access the to DJC.
Perhaps the solution is to add an option for user to enter the api key if user want to check for the license keys and expression.

**Comment by chinyeungli** [comment]
@pombredanne Let me know if this fixed the need

**Comment by pombredanne** [comment]
We should IMHO always check the validity of license_expressions and optionally we should check that the license keys are known license keys. Doing a remote check by default is not the best way IMHO.
I am not we want to have a `--check-licenses` option for now... we should spend some time to design the right set of checks we want

**Comment by pombredanne** [comment]
I am pushing this the V4 milestone. We need to discuss a bit the design of checks

**Comment by mjherzog** [comment]
We need to design a more general validation feature so that you can validate the content of your ABOUT files based on some Validation Profile. For example you could specify to validate license_expression elements against the SC LicenseDB or optionally another list. For some other fields you might just want to check for valid Boolean values or from List of Values.

**Comment by chinyeungli** [comment]
@mjherzog and @pombredanne
Should we change the `--fetch-license` option from `gen` that default to fetch from SC LicenseDB and have option to use DJC?

**Comment by mjherzog** [comment]
I think so. That fits with our overall strategy and should make it easier on first-time users.
