### ISSUE TITLE
Update ABOUT files with the latest format

### ISSUE THREAD

**Issue by chinyeungli** [aboutcode-org/aboutcode-toolkit#346]
All the ABOUT files should adapt the new multiple licenses support format. In addition, the version of the about.ABOUT also need to be updated.

**Comment by pombredanne** [comment]
One suggestion is to skip having a version here.

**Comment by chinyeungli** [comment]
The version for `about.ABOUT` is updated.
https://github.com/nexB/aboutcode-toolkit/commit/627f903c666adcf90da4e7c3ca99509dd9df2e9a

**Comment by chinyeungli** [comment]
Closing this. See #384
