### ISSUE TITLE
Rename the attributecode module to aboutcode

### ISSUE THREAD

**Issue by tdruez** [aboutcode-org/aboutcode-toolkit#347]
https://github.com/nexB/aboutcode-toolkit/tree/develop/src/attributecode

The main module name should match the library name. 
This is confusing when using aboutcode-toolkit as a library.

**Comment by tdruez** [comment]
@pombredanne Is https://github.com/nexB/aboutcode-toolkit/pull/313 properly merged?
The module name is still `attributecode` in current develop https://github.com/nexB/aboutcode-toolkit/tree/develop/src/attributecode

**Comment by pombredanne** [comment]
@tdruez #313 has not been merged and is deleted now. This is moved to v4

**Comment by pombredanne** [comment]
Fixed with #383
