### ISSUE TITLE
Package vs. component: we need to support this cleanly

### ISSUE THREAD

**Issue by pombredanne** [aboutcode-org/aboutcode-toolkit#348]
This is a design and discussion item carried from https://github.com/nexB/aboutcode-toolkit/issues/345#issuecomment-432743994:
> we have eventually package- and component-level data.
> The package would be identified by the Package URL or purl fields (type, namespace, name, version, qualifiers, subpath); and the component by its name/version.
> We would need to refine how we handle cases where we have data from both

**Comment by pombredanne** [comment]
The package part should be the main focus of V4. Support for component could go in v4.1

**Comment by mjherzog** [comment]
I think that we have evolved to a point where each item in an inventory is a Package with a purl or not (Component). We do not need to support overlap here.

**Comment by chinyeungli** [comment]
obsolete
