### ISSUE TITLE
Parenthesis is not handled correctly

### ISSUE THREAD

**Issue by chinyeungli** [aboutcode-org/aboutcode-toolkit#352]
```
ERROR: The following character(s) cannot be in the licesne_expression: ['(', ')']
```
I think it's probably my bad to have
https://github.com/nexB/aboutcode-toolkit/commit/5901f23a3aec8172ad4ba2b9f58bc1c2c51664a6#diff-7118d814610481b98680906c9c038dbe

Not sure why I did that, but in any case, parenthesis need to be supported in license_expression.

**Comment by pombredanne** [comment]
`+` and `(` and `)` should be allowed and are possible.
May be a better way to state this would be that these are only allowed: `space`, `()+-_.`, `a-z` ,`A-Z` , `0-9`

Or you could simply parse it with license-expressions?
