### ISSUE TITLE
confusion of "about_resource" and "about_resource_path"

### ISSUE THREAD

**Issue by chinyeungli** [aboutcode-org/aboutcode-toolkit#354]
These 2 seems duplicated and cause confusion.

Sample:
Assuming we want to create a common-logging.ABOUT

Project: /project/apache/commons/commons-logging/

if we put the ABOUT file under /project/apache/commons/commons-logging/:
the `about_resource` and `about_resource_path` are `.` because it's referring the current directory

if we put the ABOUT file under /project/about/:
`about_resource: commons-logging`
`about_resource_path: ../apache/commons/commons-logging/`

perhaps we don't need to have both as the value of the `about_resource` can be spotted in the `about_resource_path`.

We should just keep the `about_resource` with the `about_resource_path`’s behavior

**Comment by pombredanne** [comment]
See also #364

**Comment by pombredanne** [comment]
This is fixed now.
