### ISSUE TITLE
Add support for special characters in .ABOUT filenames

### ISSUE THREAD

**Issue by tdruez** [aboutcode-org/aboutcode-toolkit#378]
The following cases should not be considered as errors at all:
```
Running aboutcode-toolkit version 3.4.0.pre1
Checking ABOUT files...
Command completed with 113 errors or warnings.
CRITICAL: Invalid characters '()' in file name at: 'AForge.NET Framework-2.1.4-(libs only).zip.ABOUT'
CRITICAL: Invalid characters '+' in file name at: 'abstract_0.0+0.1a1-1.diff.gz.ABOUT'
CRITICAL: Invalid characters '~' in file name at: '~aacplugin-1.1-1.src.rpm.ABOUT'
CRITICAL: Invalid characters '[]' in file name at: '[3.2-3] Sublimity Gaming Dungeon Guide.exe.ABOUT'
CRITICAL: Invalid characters '++' in file name at: 'active-jms-c++-example.zip.ABOUT'
CRITICAL: Invalid characters '绿色版' in file name at: 'aftpserver1.1-绿色版.7z.ABOUT'
CRITICAL: Invalid characters '|' in file name at: 'aacgain-master.zip|.ABOUT'
[...]
```

**Comment by pombredanne** [comment]
@tdruez there was a good reason for the specification of some restrictions in ABOUT file names: we wanted these to be portable across OSes (e.g. this includes Windows). Now this creates some weirdness: this means that the name of certain .ABOUT files cannot be made of the documented file name + '.ABOUT` which is the common convention. I am OK to relax this and put aside some cross-OSes compatibility... but are we all ready for this? @DennisClark your input is welcomed

**Comment by tdruez** [comment]
@pombredanne Should we encode the filename to a string portable across OSes?

**Comment by pombredanne** [comment]
@tdruez IMHO the simplest and best way  is not to enforce any restrictions on file names, and return error when the underlying file system is not happy.

**Comment by DennisClark** [comment]
We should not allow `/`  `\`  `:` or an embedded space in the name.

**Comment by chinyeungli** [comment]
@DennisClark spaces in name are already supported https://github.com/nexB/aboutcode-toolkit/issues/310

Let me know if you think this is inappropriate.

**Comment by DennisClark** [comment]
@chinyeungli   I guess spaces in the name are ok after all !

**Comment by chinyeungli** [comment]
In the spec, we've stated that only US-ASCII characters are supported
https://github.com/nexB/aboutcode-toolkit/blob/develop/SPECIFICATION.rst#about-file-name

meaning no support for Chinese characters

@tdruez @pombredanne Should we support Chinese charas?

**Comment by chinyeungli** [comment]
@pombredanne @tdruez Do you think we should update the SPEC and support chinese characters?

**Comment by chinyeungli** [comment]
We will not support non US-ASCII characters in the filename and path.
Make sure #407 has this covered.
