### ISSUE TITLE
Update/upgrade /thirdparty/ About Files to current AbC-TK syntax/format

### ISSUE THREAD

**Issue by johnmhoran** [aboutcode-org/aboutcode-toolkit#384]
We need to update/upgrade the About Files in the `/thirdparty/` directory (and perhaps elsewhere?) to use the current AbC-TK syntax/format.

**Comment by pombredanne** [comment]
Good point. It might be best to wait for the 4.x branch to be merged in develop first though.

**Comment by mjherzog** [comment]
I think that we should have these updated for v3.3.

**Comment by chinyeungli** [comment]
I can do that once we have fixed #398

**Comment by chinyeungli** [comment]
ran the `about check thirdparty/` and no error detected.
