### ISSUE TITLE
The default required column should also be a default list of the column_filters

### ISSUE THREAD

**Issue by chinyeungli** [aboutcode-org/aboutcode-toolkit#388]
I keep getting the following error
```
CRITICAL: Row 0 is missing required values for columns: about_file_path, name
```
with the following transform config file:
```
required_columns:
    - license_expression
    
column_filters:
    - license_expression
```

Then I realize if I add the `name` and the `about_file_path` in the column_filters list, everything went fine.

Since these two fields are required by default, user should not need to put these 2 fields in the `column_filters` list.

**Comment by pombredanne** [comment]
The latest code in the ranch has been updated and the `column_filters` has been renamed to `kept_columns`.

Note that per #345 name should not be mandatory , so this live only the `about_file_path` field.

We would need to discuss this `about_file_path` field as I explained in #364  ... IMHO this should not be needed with `gen` as the placement of a generated .ABOUT file should be relative to the documented `about_resource` and therefore having an explicit `about_file_path` is a likely source of problems and confusion. In most cases the path would be the `about_resource` path with a .ABOUT extension.

**Comment by chinyeungli** [comment]
@pombredanne I don't see any `kept_columns` in the latest develop branch nor `361-make-transform-work`... has the latest code been pushed/merged?

**Comment by pombredanne** [comment]
@chinyeungli you can find the new kept columns in the `361-make-transform-work` branch... See https://github.com/nexB/aboutcode-toolkit/blob/361-make-transform-work/src/attributecode/transform.py#L123
May be you are not up to date?

**Comment by chinyeungli** [comment]
Since there is API changes, I mark this for v5 ticket.

**Comment by chinyeungli** [comment]
Not going to fix as we already have a detailed doc about what need to be included:
```
* field_filters:
An optional list of field names that should be kept in the transformed CSV/JSON. If
this list is provided, all the fields from the source CSV/JSON that should be kept
in the target CSV/JSON must be listed regardless of  either standard or required
fields. If this list is not provided, all source CSV/JSON fields are kept in the
transformed target CSV/JSON.
```
