### ISSUE TITLE
Drop ability to generate attribution from a zip

### ISSUE THREAD

**Issue by pombredanne** [aboutcode-org/aboutcode-toolkit#390]
I reckon this is a convenience, but only a small one. I would rather drop the feature and only support generating attribution from a regular set of ABOUT files in a directory tree. The user would therefore need to unzip/untar any archive first instead.

**Comment by ThomasLi2009** [comment]
@mjherzog @DennisClark any feedback on this?

**Comment by DennisClark** [comment]
Not sure why this needs to be done.

**Comment by chinyeungli** [comment]
Closing the ticket as we will keep this feature (at least for now)
