### ISSUE TITLE
Add support for `package_url` field

### ISSUE THREAD

**Issue by tdruez** [aboutcode-org/aboutcode-toolkit#395]
See for example https://github.com/nexB/aboutcode-toolkit/blob/develop/thirdparty/saneyaml-0.1-py2.py3-none-any.whl.ABOUT#L17

```
Running aboutcode-toolkit version 3.4.0.pre1
Checking ABOUT files...
INFO: saneyaml-0.1-py2.py3-none-any.whl.ABOUT: Field package_url is a custom field.
```

See also https://github.com/package-url/packageurl-python

**Comment by pombredanne** [comment]
@tdruez this make sense... though there is eventually some decision to make in terms of component (which is what name and version document in the current spec) and package (which is what a package_url documents, including name and version).

We could say that name and version apply to the package. 
And add new component_name and component_version 

Then a package_url just provides extra data? (type, qualifier, subpath?)
Instead allow to state each Package URL attribute as its own field?

**Comment by chinyeungli** [comment]
any decision?

**Comment by chinyeungli** [comment]
This is the purl spec: https://github.com/package-url/purl-spec
