### ISSUE TITLE
Design support for alternative output for Android

### ISSUE THREAD

**Issue by pombredanne** [aboutcode-org/aboutcode-toolkit#396]
Android has it's own attribution generation toolkit based on a combo of MODULE_LICENSE_XXX empty tag files and NOTICE files.
We could easily devise a way to create such files as an alternative to or in addition to the creation of ABOUT files. The be fit would be that the generated files when included in a codebase would participate naturally in Android attribution generation syste,

**Comment by pombredanne** [comment]
Here is what I think could work out nicely:

Add a `--android` option to the `gen` sub-command (and possibly other sub-commands too) such that we generate  MODULE_LICENSE_XXX files that will contain the YAML data usually saved in .ABOUT files. Also generate and/or create a NOTICE for each MODULE_LICENSE file.
Then these can be committed in an Android code tree tree.

With that, the Android attribution can then be generated by Android build system.

**Comment by mjherzog** [comment]
So the MODULE_LICENSE_XXX files will not be empty as is the normal case for Android?

**Comment by pombredanne** [comment]
@mjherzog  that would be the idea: a MODULE_LICENSE_XXX file would becomes effectively an alternative file name for .ABOUT file

**Comment by pombredanne** [comment]
@pombredanne that would be the idea: a MODULE_LICENSE_XXX file would becomes effectively an alternative file name for .ABOUT file

**Comment by pombredanne** [comment]
We would need to establish some mapping between the `XXX` of MODULE_LICENSE_XXX and actual real licenses.
Here is a list of known file names collected from a recent Android tree:
```
MODULE_LICENSE_APACHE
MODULE_LICENSE_APACHE2
MODULE_LICENSE_APL
MODULE_LICENSE_BSD
MODULE_LICENSE_BSD_LIKE
MODULE_LICENSE_BSD_LIKE_AND_APACHE_2
MODULE_LICENSE_BSD_OR_LGPL
MODULE_LICENSE_CPL
MODULE_LICENSE_EPL
MODULE_LICENSE_FRAUNHOFER
MODULE_LICENSE_GPL
MODULE_LICENSE_GPL_WITH_CLASSPATH_EXCEPTION
MODULE_LICENSE_HP
MODULE_LICENSE_HPND
MODULE_LICENSE_LGPL
MODULE_LICENSE_MIT
MODULE_LICENSE_MPL
MODULE_LICENSE_MPL2
MODULE_LICENSE_MPL_GPL_LGPL
MODULE_LICENSE_NOTICE
MODULE_LICENSE_OFL
MODULE_LICENSE_PERMISSIVE
MODULE_LICENSE_PUBLIC_DOMAIN
MODULE_LICENSE_UNICODE
MODULE_LICENSE_UNIVERSITIES
MODULE_LICENSE_W3C
MODULE_LICENSE_ZLIB
``` 

Also Android does not care about the content of these MODULE_LICENSE files.

We will need to craft a NOTICE file for each "component" that is basically a generated attribution for that component that would contain all the copyrights, notices and the license texts of that component.

**Comment by pombredanne** [comment]
Actually no mapping is needed because there is mostly no meaning attached to the  `XXX` part in a `MODULE_LICENSE_XXX` file name except for anything with `GPL`, `LGPL` or `MPL` in it.

So we could very much use a license expression or the primary license, made uppercase and with dash and spaces and dots replaced by underscore just to look similar and consistent. Or just uppercase and remove spaces: MODULE_LICENSE_GPL-3.0_WITH_GCC-LINKING-EXCEPTION-3.1 would be perfectly OK :+1: AFAIK

**Comment by pombredanne** [comment]
It seems possible to have more than one MODULE_LICENSE_XXX file per module. See https://android.googlesource.com/platform/prebuilts/misc/+/brillo-m7-release/darwin-x86_64/swig

**Comment by pombredanne** [comment]
And some pointers:

https://android.googlesource.com/platform/build/+/master/core/base_rules.mk#172
https://android.googlesource.com/platform/build/+/master/core/notice_files.mk
https://android.googlesource.com/platform/build/+/master/tools/print_module_licenses.sh

and of course:
https://softwareengineering.stackexchange.com/questions/234025/what-is-the-meaning-of-module-license-bsd-like-in-android-source-code

https://web.archive.org/web/20150523042805/http://www.dejacode.org/android_case_study.html :D

And this is an example: https://android.googlesource.com/platform/external/webkit/+/master


Note that based on this https://android.googlesource.com/platform/build/+/master/core/base_rules.mk#191 ...
```
license_files := $(call find-parent-file,$(LOCAL_PATH),MODULE_LICENSE*)
gpl_license_file := $(call find-parent-file,$(LOCAL_PATH),MODULE_LICENSE*_GPL* MODULE_LICENSE*_MPL* MODULE_LICENSE*_LGPL*)
ifneq ($(gpl_license_file),)
  my_module_tags += gnu
  ALL_GPL_MODULE_LICENSE_FILES := $(sort $(ALL_GPL_MODULE_LICENSE_FILES) $(gpl_license_file))
endif
```
... I think that the XXX in MODULE_LICENSE is purely indicative and could be anything. Only GPL/LGPL/MPL have a meaning (e.g. copyleft code)
