### ISSUE TITLE
Gen from scancode JSON does not work

### ISSUE THREAD

**Issue by pombredanne** [aboutcode-org/aboutcode-toolkit#401]
Reported privately:
>  I'm getting an error 'CRITICAL: The essential field 'about_file_path' is not found.'  Not sure what I'm missing or the necessary workflow steps.
> Currently I have the output files from scancode-toolkit.
> Previously we went from scancode to aboutcode.
> This is with aboutcode-toolkit-3.3.2 and scancode-toolkit-2.9.2
> Scanned to json-pp and trying to generate about files
/opt/scancode/scancode-toolkit-2.9.2/scancode -l -p -c --json-pp ~/src/scancode.json ~/src/codebase/
./about gen ~/src/scancode.json ~/src/about

**Comment by chinyeungli** [comment]
#364 is fixed and the `about_file_path` is no longer needed for the input.
