### ISSUE TITLE
Invalid info message when boolean field is false

### ISSUE THREAD

**Issue by grv87** [aboutcode-org/aboutcode-toolkit#403]
`boolean_false.ABOUT` file:
```
about_resource: boolean_false.ABOUT
name: boolean_false
internal_use_only: false
```

Using `develop` branch, run:
```
# about check --verbose boolean_false.ABOUT
Running aboutcode-toolkit version 4.0.0.pre1
Checking ABOUT files...
INFO: about/boolean_false.ABOUT: Field internal_use_only is present but empty.
```

But field is present and not empty!

I agree with @chinyeungli's https://github.com/nexB/aboutcode-toolkit/issues/327#issuecomment-419363434:
> I think if users put a "No" or false value in the boolean field, they mean to put it there 

Related: #326, #327.

**Comment by chinyeungli** [comment]
Thanks for the report. I will look at this.

**Comment by chinyeungli** [comment]
For some reasons, the fixes at https://github.com/nexB/aboutcode-toolkit/commit/c6a05b85b2be3fb6caad20b0540124506dd8fcc8 are not in the current code.
