### ISSUE TITLE
Rename configuration key for `transform`

### ISSUE THREAD

**Issue by chinyeungli** [aboutcode-org/aboutcode-toolkit#418]
The current configuration for `transform` are:
```
column_renamings:
column_filters:
required_columns:
```
However, since the `transform` now works with JSON file (not only CSV), perhaps we should rename these keys as the word `column` doesn't make sense for JSON file.

**Comment by srthkdb** [comment]
@chinyeungli As discussed, I have renamed column_renamings, required_columns, and column_filters to field_renamings, required_fields, and field_filters respectively. Please see the PR https://github.com/nexB/aboutcode-toolkit/pull/419

**Comment by chinyeungli** [comment]
This has been fixed.
