### ISSUE TITLE
`delete_files` command for `transform`

### ISSUE THREAD

**Issue by srthkdb** [aboutcode-org/aboutcode-toolkit#423]
In [Issue #416 (JSON output form scancode toolkit doesn't work as the input for `gen`)](https://github.com/nexB/aboutcode-toolkit/issues/416), we would like to delete files items with low license score. To do this, a `delete_files` command for `transform` would be needed, as the current version of transform cannot remove items from a list. Should this feature be added because we might end up making aboutcode-toolkit more complicated than it was originally intended to be?

**Comment by chinyeungli** [comment]
I think this featuer makes aboutcode-tk more complicated than it originally intended to be, but this is open for discussion.

**Comment by chinyeungli** [comment]
I don't think this is needed. Closing it.
