### ISSUE TITLE
Publish doc on readthedocs.io

### ISSUE THREAD

**Issue by pombredanne** [aboutcode-org/aboutcode-toolkit#424]

**Comment by pombredanne** [comment]
Per @chinyeungli  it looks like  https://aboutcode-toolkit.readthedocs.io is already taken...
this was published by https://github.com/juanito-eng/aboutcode-toolkit/
@juanito-eng I guess you were trying to publish some doc there?
Do you mind to hand back over aboutcode-toolkit at readthedocs?
Thanks!

**Comment by chinyeungli** [comment]
@juanito-eng doesn't have any activity since last Dec in 2019. :(

**Comment by chinyeungli** [comment]
https://docs.readthedocs.io/en/stable/support.html
>User Support
If you need a specific request for your project or account, like more resources, change of the project’s slug or username. Send an email to support@readthedocs.org. We will get to you as soon as possible.

Perhaps time to send an email:  support@readthedocs.org

**Comment by chinyeungli** [comment]
closing this as a dup of #120
