### ISSUE TITLE
Should `transform` be designed specifically for inputs from ScanCode and AboutCode TK, or for any CSV/JSON file.

### ISSUE THREAD

**Issue by srthkdb** [aboutcode-org/aboutcode-toolkit#425]
The current version of `transform` works only for CSV/JSON output files from ScanCode and AboutCode TK. Should it be redesigned to transform any CSV or JSON, or should it be kept as it is? This issue already came up on issue #417, and its support was kept limited to AboutCode and ScanCode files, because of the reasons discussed in [this](https://github.com/nexB/aboutcode-toolkit/issues/417#issuecomment-597723180) particular comment. Now, it came up again while discussing whether the `transform` should check that the transformed output contains essential fields (`about_resource` and `name`) or not. It currently does not produce any output if essential fields are missing in the output. Please give your humble opinions!

**Comment by chinyeungli** [comment]
The current code is able to transform json from scancode-toolkit, regular json and csv files. So, I think we are fine here.
On the other hand, for the essential field, I think it's okay to check for essential field and will produce nothing if the essential field is missing as the purpose of the `transform` is to make the input work for aboutcode-tk. If the output of the "transformed" csv/json doesn't work as the input for aboutcode-tk, there is no reason to use the `transform`
