### ISSUE TITLE
Import from scancode-toolkit ?

### ISSUE THREAD

**Issue by OctagonHex** [aboutcode-org/aboutcode-toolkit#430]
Hello,
I use scancode-toolkit to gather licenses for my project (a 3rd party project with binaries -> need the binary scanner from scancode-toolkit).
How can use the output of scancode-toolkit (JSON) as an input to aboutcode-toolkit to generate a simple attribution notice file?

**Comment by chinyeungli** [comment]
Thanks for the ticket. Unfortunately, it doesn't support scancode's output as the input for aboutcode toolkit at the moment.
See https://github.com/nexB/aboutcode-toolkit/issues/416 for more information.

**Comment by chinyeungli** [comment]
closing this as a dup.
