### ISSUE TITLE
IOError when using --reference

### ISSUE THREAD

**Issue by OctagonHex** [aboutcode-org/aboutcode-toolkit#431]
On Windows 10, when using the --reference option and either the license_file or notice_file entry in the .CSV is empty the following error will be displayed on the console.

Please check if a file field is empty before trying to open it.

Example:
`about gen --reference C:\Source\Code\RefText C:\Source\Code\test.csv  C:\Source\AboutCode-Toolkit-Output
`
[test.csv.txt](https://github.com/nexB/aboutcode-toolkit/files/5028559/test.csv.txt)

```
IOError(13, 'Permission denied')
Cannot copy file at u'\\\\?\\C:\\Source\\Code\RefText
```

**Comment by OctagonHex** [comment]
Was this fixed?
Did you reproduce the error?
Did I do something wrong?

**Comment by OctagonHex** [comment]
Here is an example. When not using the reference option, everything looks fine. But with the reference option, it tries to open files with an empty file name.

```
(aboutcode-toolkit) C:\temp>about gen  test.csv .\AboutTool-Output
Running aboutcode-toolkit version 4.0.2
Generating .ABOUT files...
1 .ABOUT files generated in C:\temp\AboutTool-Output.

(aboutcode-toolkit) C:\temp>about gen  --reference .\AboutTool-ReferenceTexts test.csv .\AboutTool-Output
Running aboutcode-toolkit version 4.0.2
Generating .ABOUT files...
IOError(13, 'Permission denied')
Cannot copy file at u'\\\\?\\C:\\temp\\AboutTool-ReferenceTexts'.
IOError(13, 'Permission denied')
Cannot copy file at u'\\\\?\\C:\\temp\\AboutTool-ReferenceTexts'.
1 .ABOUT files generated in C:\temp\AboutTool-Output.
```
[test.csv.txt](https://github.com/nexB/aboutcode-toolkit/files/5032761/test.csv.txt)

**Comment by chinyeungli** [comment]
@OctagonHex Yes. It's fixed at https://github.com/nexB/aboutcode-toolkit/commit/2f48a6a20ad472963c679eb2e3ae43e3c609b353
I've added code to check if the "_file" field is empty or not before doing the copy.
The fix is in the develop branch and will be pushed to a new release later.

**Comment by OctagonHex** [comment]
Thank you!
