### ISSUE TITLE
Bug in generation of license_key_name: removes characters from middle of string!

### ISSUE THREAD

**Issue by DorsalGreen** [aboutcode-org/aboutcode-toolkit#439]
This line in attrib.py contains a bug that will result in incorrect values.
`license_key = license_text_name.strip('.LICENSE')`
The intent is to remove the the file extension, but it will remove all the characters given from the _whole_ string!
The correct way to split the string is:
`license_key = license_text_name.rsplit('.', 1)[0]`

Steps to reproduce (in pyhton):
create a file that will result in:
```
license_text_name='OFL-1.1-RFN.LICENSE'
click.echo(license_text_name.strip('.LICENSE'))
```

Output is:
`OFL-1.1-RF`
instead of
`OFL-1.1-RFN`

**Comment by chinyeungli** [comment]
Thanks for catching the bug.
For reference: https://docs.python.org/3/library/stdtypes.html#str.strip
