### ISSUE TITLE
`gen` should not accept comma in the license_key field

### ISSUE THREAD

**Issue by chinyeungli** [aboutcode-org/aboutcode-toolkit#442]
See related https://github.com/nexB/aboutcode-toolkit/issues/441 which cause weird behavior.

**Comment by OctagonHex** [comment]
If you disallow this, how can I attach more than one license to a component?
I wanted to have one component with 3 license keys and licenses.
Like this: "This component is licensed:
GPLv2-licence-name
<GPLv2 text>
MIT-license-name
<MIT text>
BSD-licence-name
<BSD text>

**Comment by chinyeungli** [comment]
@OctagonHex The correct format is to use a line break instead of comma
See https://github.com/nexB/aboutcode-toolkit/issues/441#issuecomment-682440148

**Comment by OctagonHex** [comment]
Based on the changelog entry in CHANGELOG.rst 
`    * Use ',' to support multiple files #404` (#404 )
I thought a comma was valid. But now looking at the issue, it seems that's only for JSON.

One real problem I have is, that Excel doesn't handle export of line-breaks in CSV files very badly. I have to find a way around editing the file afterwards by hand.

**Comment by chinyeungli** [comment]
@OctagonHex sorry for the bad wording. The "multiple files support" meant the `*_file` fields, not the license_key (as you can see from https://github.com/nexB/aboutcode-toolkit/issues/404#issuecomment-505332054 )
