### ISSUE TITLE
Reset command prompt after program exit (cmd.exe, Windows 10)

### ISSUE THREAD

**Issue by OctagonHex** [aboutcode-org/aboutcode-toolkit#445]
After about.exe is finished, the command promt ("PROMPT" variable) is not restored to the original value.
I think activate.bat already saves the old command prompt, but it is never restored.

Windows 10
start cmd.exe

```
C:\aboutcode-toolkit>

C:\aboutcode-toolkit> about
Usage: about [OPTIONS] COMMAND [ARGS]...
[...]

(aboutcode-toolkit) C:\aboutcode-toolkit>
```

There is already a deactivate.bat, but it is never called from about.bat.

I created a patch to fix this problem
```
diff --git "a/about.bat" "b/about.bat"
index db9ac15..d98d638 100644
--- "a/about.bat"
+++ "b/about.bat"
@@ -31,5 +31,6 @@ goto about
 call %ABOUT_ROOT_DIR%\Scripts\activate
 echo %ABOUT_ROOT_DIR%\bin\about %CMD_LINE_ARGS%
 %ABOUT_ROOT_DIR%\bin\about %CMD_LINE_ARGS%
+call %ABOUT_ROOT_DIR%\Scripts\deactivate
 
 :EOS

```

**Comment by chinyeungli** [comment]
@OctagonHex Our intention is to use `about` any where when it's activated (activated means the "PROMPT" variable is active).  For instance, in your case, you can in `about` at 
```
(aboutcode-toolkit) C:\aboutcode-toolkit>
```
you can also run `about` under `C:\` such as
```
(aboutcode-toolkit) C:\aboutcode-toolkit>
(aboutcode-toolkit) cd C:\

(aboutcode-toolkit) C:\>about
Usage: about [OPTIONS] COMMAND [ARGS]...
[...]

(aboutcode-toolkit) C:\>
```
If you want to "restore to the original value", you can type `deactivate`
i.e.
```
(aboutcode-toolkit) C:\>deactivate
C:\>
```

**Comment by OctagonHex** [comment]
Hmm, that's an interesting thought. But If the user needs to type `deactivate`, I would assume that he should have typed `activate`  first. 
Most of the other programs I know, require you to include them in the PATH if you want to have access to them from everywhere.

```
C:\aboutcode-toolkit> set PATH=C:\aboutcode-toolkit;%PATH%
cd C:\
C:\>about
Usage: about [OPTIONS] COMMAND [ARGS]...
[...]

(aboutcode-toolkit) C:\>
```

**Comment by chinyeungli** [comment]
Re the requirement to set the "environment variable path", this is an approach for easier use.
i.e. if users don't want to edit the "environment variable path", they can use this approach, and of course, they can always add the `about.exe` to the "environment variable path" as well...

as you can see from https://github.com/nexB/aboutcode-toolkit/blob/develop/configure.bat#L60 , the script automatically runs the `activate`. If users `deactivate` (as mentioned above) and want to re-activate, they can do
```
C:\aboutcode-toolkit>bin\activate
(aboutcode-toolkit) C:\aboutcode-toolkit>
```
and then `about` will be able to run anywhere again.

**Comment by pombredanne** [comment]
@chinyeungli I think that you should NOT activate the virtualenv in your about.bat script, instead you should use a similar pattern to what's used in ScanCode at https://github.com/nexB/scancode-toolkit/blob/develop/scancode for POSIX and at https://github.com/nexB/scancode-toolkit/blob/develop/scancode.bat for Windows

This would mean not activating and calling the generated `Scripts\about` entry point directly.
This was there is never any prompt change. That generated script knows everything about the virtualenv already

**Comment by chinyeungli** [comment]
@pombredanne isn't the `scancode.bat` calls the `configure.bat` which then activate the virtualenv ?

https://github.com/nexB/scancode-toolkit/blob/develop/scancode.bat#L21
https://github.com/nexB/scancode-toolkit/blob/develop/scancode.bat#L28
https://github.com/nexB/scancode-toolkit/blob/develop/configure.bat#L154

**Comment by pombredanne** [comment]
@chinyeungli good point. You can have a version on your side that does not activate if that's an issue. 
Or you could deactivate after you ran scancode there: https://github.com/nexB/scancode-toolkit/blob/c3c92ff121632ea5db835f1c460c7d483a91a5d6/scancode.bat#L39
But that might be surprising to someone that did activate by hand
