### ISSUE TITLE
Enable Homepage URL (or other fields) to identify owner/provenance as alternative to Copyright

### ISSUE THREAD

**Issue by mjherzog** [aboutcode-org/aboutcode-toolkit#448]
Most of our Attribution Notice templates are based on the idea that you will report Copyright Notice or Holder with the License to indicate the ownership/origin of a component or package. This is not practical for cases like npm packages where copyright information is typically missing or very hard to identify.  We need enhancements to support Attribution where you may report Copyright information for some components/packages and Homepage or other URL for other components/packages.

This could be accomplished in different ways:
- Conditional logic based on the data available where you report Copyright if available and URL if not, OR
- Expand the Attribution data to report URL in addition to Copyright for all Items, OR
- ?

**Comment by chinyeungli** [comment]
I believe either way can be done by updating the template.
I vote for 2nd choice. i.e. to report both copyright (if any) AND homepage_url (if any) for consistency perspective.

**Comment by DennisClark** [comment]
Simplest approach is to setup the attribution template(s) such that: 
* if there is a homepage url, print it
* if there is a copyright, print it
No problem if both exist.

**Comment by mjherzog** [comment]
Ok - lets try that first.

**Comment by chinyeungli** [comment]
@mjherzog I believe we can close this?

**Comment by chinyeungli** [comment]
Closing this as this can be handled in a template.
