### ISSUE TITLE
Special characters for filename

### ISSUE THREAD

**Issue by chinyeungli** [aboutcode-org/aboutcode-toolkit#451]
The current spec allows the following symbols: `"_", "-", "+", ".", "(", ")", "~", "[", "]", "{", "}"`
https://github.com/nexB/aboutcode-toolkit/blob/develop/SPECIFICATION.rst#about-file-name

However, I am still able to generate ABOUT files with `!` and `@`, but it fails when doing `attrib`.
Note that `!` is likely not allowed in linux system, but `@` seems is accepted in both linux and windows as filename
Should we allow more special characters for filename?

**Comment by DennisClark** [comment]
@chinyeungli    I just saved a file on the Mac with filename = `licenseref@example.png`  
and it saved with no problems 
and I can open it and edit it with no problems. 
So I am all in favor of allowing the `@` character in an about-file-name.
