### ISSUE TITLE
Update Reference documentation to match current version

### ISSUE THREAD

**Issue by mjherzog** [aboutcode-org/aboutcode-toolkit#452]
The current doc we have at https://aboutcode.readthedocs.io/en/latest/aboutcode-toolkit/reference.html is very far out of date. For example we no longer have mapping files. We need to urgently update this doc in place to match version 5.
We need to effectively "jump" from the current doc (which should be version 3) to version 5 and keep the doc reasonably current as we go forward.
This is separate from recovering our RTD page for aboutcode-toolkit.

**Comment by chinyeungli** [comment]
RDT doc updated. See https://github.com/nexB/aboutcode/compare/d9eaa96e9111...1f0c6248637c
