### ISSUE TITLE
Regression: Errors when generating attribution document

### ISSUE THREAD

**Issue by OctagonHex** [aboutcode-org/aboutcode-toolkit#454]
The newest version introduces a bug that causes some severe error when generating the attribution notice

`cd aboutcode-toolkit`

`about attrib --template templates\default_html.template example\e2fsprogs-1.39\e2fsprogs-about\e2fsprogs-1.39 example\e2fsprogs-1.39\output\test.html`

>bad with commit: eb1a2fad1df9ec992927c4cdc8f5fa5eacd1bbb2
>last know commit where it worked correctly : 14a646e8a4bfe2384d768b866f7b26052b3906c7

The error is:

```
Running aboutcode-toolkit version 5.1.0
Generating attribution...
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
None

<!doctype html>
<html>
  <head>
[...]
```

**Comment by chinyeungli** [comment]
My bad. I forgot to remove the print statements which was used for debugging..
