### ISSUE TITLE
refactoring the code and remove the `attrib` options

### ISSUE THREAD

**Issue by chinyeungli** [aboutcode-org/aboutcode-toolkit#458]
The `attrib` feature will be in a separate repo/project. We probably want to remove this features in AboutCode TK and focus the attribution function in one place.

**Comment by mjherzog** [comment]
Agreed, but we do not want to do this until we have AttributeCode fully functional and released.

**Comment by mjherzog** [comment]
This issue is moot because we decided to keep the `attrib` featurefeature in ACTK.
