### ISSUE TITLE
AboutCode Toolkit latest version is not updated.

### ISSUE THREAD

**Issue by s4-2** [aboutcode-org/aboutcode-toolkit#460]
- In [AboutCode Toolkit](https://www.aboutcode.org/projects/aboutcode-toolkit.html) it seems that the latest version of AboutCode Toolkit is not updated. 
- The latest version of AboutCode Toolkit is  [v5.1.0](https://github.com/nexB/aboutcode-toolkit) .

**Comment by prykdev** [comment]
Can i work on this issue ?

**Comment by s4-2** [comment]
@P-riyanka-prasad  Thanks for showing interest to solve this issue. If you too find this issue relevant you can go ahead:)

**Comment by MUzairS15** [comment]
Where can i find file for this. Pls help

**Comment by chinyeungli** [comment]
This issue should be address at https://github.com/nexB/aboutcode/issues/69
