### ISSUE TITLE
Compatible to use About File as input

### ISSUE THREAD

**Issue by chinyeungli** [aboutcode-org/aboutcode-toolkit#497]
Updated:
AttributeCode should be able to use About File as an input for attribution generation.

Old Description: User should be able to use the same template from AboutCode Toolkit in AttributeCode.

**Comment by chinyeungli** [comment]
The way the get the license information for `attrib` between `AttributeCode` and `AboutcodeToolkit` is different. 
`AttributeCode` get the license information directly from `LicenseDB` and then pass the information to the template as a dictionary while `AboutcodeToolkit` get the license information and then save it along with the about object (i.e. about.license_text etc). Therefore, the same template cannot be used in both places.

After some thoughts, it makes no sense to save the license's information in the about object as the same way as in the `AboutcodeToolkit`, but it makes more sense in the `AboutcodeToolkit` side to pass a license dictionary to the template as same as in the `AttributeCode`. 

As a result, https://github.com/nexB/aboutcode-toolkit/issues/459 should be fixed first

**Comment by mjherzog** [comment]
I am not sure how important it is to re-use template from ABCTK without any changes. At a higher level we want AttributeCode to replace the Attribution generation from ABCTK and About files. I was expecting that there would be some way to "read" About files from AttributeCode as if the About files were some sort of database (like LicenseDB).

**Comment by chinyeungli** [comment]
okay. It's not currently support reading ABOUT files.
@mjherzog To make things a bit clear, the input file can be CSV, Excel, JSON and ABOUT files. The attributecode will only generate attribution notice and nothing more?

**Comment by mjherzog** [comment]
The focus of AttributeCode should be just generating Attribution docs with various inputs (CSV, Excel, JSON and ABOUT files) and various outputs (from the templates). The tricky part is how to get the license information for licenses not in LicenseDB. I suspect that we will need to update ABCTK to provide the inputs, but we will remove Attribution from ABCTK and migrate templates as needed.

**Comment by chinyeungli** [comment]
We can close this issue as we no longer support `attributeCode`
