### ISSUE TITLE
Identify and create input spreadsheet files to feed attributecode

### ISSUE THREAD

**Issue by DennisClark** [aboutcode-org/aboutcode-toolkit#499]
Identify and create input spreadsheet files to feed attributecode for testing purposes. 
* keep in mind that one or more of them will become test files. 
* also note that attributecode will be made publicly available

**Comment by DennisClark** [comment]
Note that the input spreadsheets should include: 
* simple stuff (e.g. component names+versions)
* purl values
* license expressions
* anything needed to test the basic functionality

**Comment by DennisClark** [comment]
Since we are the primary current users of AbC Toolkit, we should plan for the following success criteria for AttributeCode v1.0 to be the capability to produce useful and accurate Attribution Notices from:
* An Inventory or BOM file for a product
* One or more nexB FOSS products - e.g. Scancode TK and vulnerablecode

**Comment by chinyeungli** [comment]
I've already provided some samples at https://github.com/nexB/attributecode/tree/main/samples

Perhaps we can close this if we are satisfy with the output?

**Comment by chinyeungli** [comment]
This was a `attributecode` ticket as no longer valid as it's merged into aboutcode-tk
