### ISSUE TITLE
add list of supported SCM tools

### ISSUE THREAD

**Issue by chinyeungli** [aboutcode-org/aboutcode-toolkit#5]
add list of supported SCM tools and raise warning if not found: cvs, svn, git, arch, hg, bzr, darcs, clearcase, perforce

**Comment by chinyeungli** [comment]
@pombredanne do we still want to have these support?

**Comment by pombredanne** [comment]
A validation is not needed there IMHO so I am closing for now as wontfix. Feel free to reopen, of course!
