### ISSUE TITLE
Implement command line options using argparse module

### ISSUE THREAD

**Issue by jdaguil** [aboutcode-org/aboutcode-toolkit#7]
The argparse module allows easy implementation of optional and positional parameters and also handles the output formatting.

**Comment by jdaguil** [comment]
This module is only included in python >= 2.7

**Comment by pombredanne** [comment]
@jdaguil good point ... yet it will not be possible for long to keep a single script approach IMHO and the tool will need to use thirdparty libraries at some time. For instance argparse is also a separate package: https://pypi.python.org/pypi/argparse/1.2.1 ... So I would like to keep this open for now if this works for you

**Comment by chinyeungli** [comment]
@pombredanne Do we still want to keep this open?

**Comment by JonoYang** [comment]
We are using click for cli options. Closing.
