### ISSUE TITLE
Pass as an option a list of fields that are mandatory

### ISSUE THREAD

**Issue by pombredanne** [aboutcode-org/aboutcode-toolkit#9]
I would like to have a configurable command line option to pass a list of fields considered as mandatory overriding the basics... This is important because for a certain usage certain fields will be needed. For instance generating attribution or redistribution requires certain fields to be set which may be otherwise considered as optional.

**Comment by chinyeungli** [comment]
@pombredanne Can you provide some use cases?

**Comment by chinyeungli** [comment]
@pombredanne If I understand correctly, you'll like the tool to treat certain key as mandatory if user provide a list of key(s).
For instance,
if user wants the `version` be mandatory, the tool will validate if the input has the version field and throw error if the version field is not present or empty?

**Comment by pombredanne** [comment]
This will not be implemented.
