### ISSUE TITLE
Notices are not created in attribution file from notice_file.

### ISSUE THREAD

**Issue by jdaguil** [aboutcode-org/aboutcode-toolkit#96]
In an about file, when the 'notice_file' field points to a file location with notice text in it, attribution is not created.  However, it does works for the 'notice' field.

**Comment by DennisClark** [comment]
If this is still a bug, it should be a high priority.  I will re-test and report the results.

**Comment by DennisClark** [comment]
This is no longer a problem as of about-code-tool-1.0.2. You can see that in the example e2fsprogs-1.39 that we have posted.  The 32fsprogs-1.39.ABOUT file contains the following line: 

notice_file: e2fsprogs-1.39.NOTICE 

and if you look at the sample_attribution_starship.html  you will see that the text of that .NOTICE file appears right after the entry for the component.     Closing.
